/**
 * MONO — 数据生成器
 * 生成 src/data/catalog-cs2.js / catalog-compute.js / catalog-hardware.js / catalog-assets.js
 * 数据为静态常量表，本脚本只在维护数据时运行：
 *   node scripts/gen-catalog.mjs
 * 生成结果可提交入库；游戏运行时不依赖本脚本。
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'src/data');

/* ------------------------------------------------------------------ 记录 */
// [id, name, subType, rarity, price, {float,st,pattern,desc,vol,unit,mkt}]
const CS2 = [];
const COMPUTE = [];
const HARDWARE = [];
const ASSETS = [];

const W = (arr, ...rows) => rows.forEach((r) => arr.push(r));

/* =========================== CS2 饰品 (300) =========================== */
// 白 —— 几毛到几块的消费级/工业级
W(CS2,
  ['p250-sand-dune', 'P250 | 沙丘之刃', '手枪', 'white', 0.35, { float: 1, st: 1, desc: '最常见的入门皮肤，流通量极大，价格几乎不动。' }],
  ['mp9-storm', 'MP9 | 暴风', '微型冲锋枪', 'white', 0.42, { float: 1, st: 1, desc: '工业级喷漆，箱子开箱副产物，长期横盘。' }],
  ['scar20-jungle', 'SCAR-20 | 丛林风暴', '狙击枪', 'white', 0.48, { float: 1, st: 1, desc: '冷门枪械的低级皮肤，有价无市是常态。' }],
  ['ssg08-blue-spruce', 'SSG 08 | 蓝色云杉', '狙击枪', 'white', 0.55, { float: 1, st: 1, desc: '消费级迷彩，起步阶段的填充库存。' }],
  ['galil-cerberus', 'Galil AR | 地狱犬', '步枪', 'white', 0.6, { float: 1, st: 1, desc: '军规级底价款，通胀后仍稳定在几毛钱区间。' }],
  ['m249-aztec', 'M249 | 阿兹特克', '机枪', 'white', 0.7, { float: 1, st: 1, desc: '机枪皮肤需求极低，流动性差，回收价压得最狠。' }],
  ['negev-army-sheen', 'Negev | 陆军之辉', '机枪', 'white', 0.75, { float: 1, st: 1, desc: '工业级机枪，几乎只在开箱池里被顺手开出。' }],
  ['famas-cyanospatter', 'FAMAS | 青蓝斑纹', '步枪', 'white', 0.8, { float: 1, st: 1, desc: '冷门步枪皮肤，价格多年维持在开箱成本以下。' }],
  ['sg553-waves', 'SG 553 | 波浪', '步枪', 'white', 0.9, { float: 1, st: 1, desc: '消费级图案，适合作为分解材料。' }],
  ['sawedoff-forest', 'Sawed-Off | 森林 DDPAT', '霰弹枪', 'white', 1.05, { float: 1, st: 1, desc: '经典迷彩，随老箱子停落后缓慢抬价。' }],
  ['mag7-swat', 'MAG-7 | 特警', '霰弹枪', 'white', 1.15, { float: 1, st: 1, desc: '工业级配色，成交零散。' }],
  ['nova-predator', 'Nova | 掠食者', '霰弹枪', 'white', 1.25, { float: 1, st: 1, desc: '老牌低级霰弹皮肤，供给长期过剩。' }],
  ['xm1014-blue-steel', 'XM1014 | 蓝钢', '霰弹枪', 'white', 1.4, { float: 1, st: 1, desc: '开箱池常客，价格随箱子热度小幅波动。' }],
  ['p2000-grassland', 'P2000 | 草原', '手枪', 'white', 1.5, { float: 1, st: 1, desc: '消费级手枪皮，偶有模板溢价。' }],
  ['cz75-tread', 'CZ75-Auto | 军绿纹', '手枪', 'white', 1.6, { float: 1, st: 1, desc: '冷门自动手枪，挂单堆积严重。' }],
  ['tec9-varicamo', 'Tec-9 | 都市危机', '手枪', 'white', 1.75, { float: 1, st: 1, desc: '都市迷彩，价格与开箱量直接相关。' }],
  ['mp7-forest', 'MP7 | 森林 DDPAT', '微型冲锋枪', 'white', 1.9, { float: 1, st: 1, desc: '老皮肤，靠停落缓慢升值。' }],
  ['ump45-scorched', 'UMP-45 | 灼烧', '微型冲锋枪', 'white', 2.1, { float: 1, st: 1, desc: '工业级，几块钱的稳定标的。' }],
  ['p90-teardown', 'P90 | 拆解', '微型冲锋枪', 'white', 2.3, { float: 1, st: 1, desc: '经典冷门设计，成交量低。' }],
  ['mac10-candy', 'MAC-10 | 硬糖', '微型冲锋枪', 'white', 2.5, { float: 1, st: 1, desc: '入门皮肤里少有的热门枪型，价格有支撑。' }],
  ['ppbizon-facility', 'PP-巴拉克拉瓦 | 设施系列', '微型冲锋枪', 'white', 2.8, { float: 1, st: 1, desc: '地图系列皮肤，价格随大行动热度波动。' }],
  ['elites-soil', '双持贝瑞塔 | 深红土壤', '手枪', 'white', 3.1, { float: 1, st: 1, desc: '冷门双持，常年无人问津。' }],
  ['fiveseven-candy', 'Five-SeveN | 硬糖', '手枪', 'white', 3.5, { float: 1, st: 1, desc: '低端皮肤的流动性样本。' }],
  ['r8-bone', 'R8 左轮 | 骨形面具', '手枪', 'white', 4.2, { float: 1, st: 1, desc: '冷门左轮，偶尔被收藏者扫货。' }],
  ['m4a1s-varied', 'M4A1-S | 变色龙', '步枪', 'white', 4.8, { float: 1, st: 1, desc: '入门步枪皮，池子里最容易被抽到的步枪。' }],
  ['ak47-first', 'AK-47 | 荒野反抗', '步枪', 'white', 5.5, { float: 1, st: 1, desc: 'AK 的最低档皮肤，出货量大。' }],
  ['awp-worm', 'AWP | 蠕虫之神', '狙击枪', 'white', 6.2, { float: 1, st: 1, desc: 'AWP 入门款，新手常驻库存。' }],
  ['deagle-mudder', 'Desert Eagle | 泥地杀手', '手枪', 'white', 6.9, { float: 1, st: 1, desc: '沙鹰低端款，价格与开箱率挂钩。' }],
  ['glock-bunsen', 'Glock-18 | 本生灯', '手枪', 'white', 7.6, { float: 1, st: 1, desc: '军规级入门，价格波动温和。' }],
  ['usp-blueprint', 'USP-S | 蓝图', '手枪', 'white', 8.4, { float: 1, st: 1, desc: '低调设计，但因枪型热门而有溢价。' }],
  ['aug-commander', 'AUG | 指挥官', '步枪', 'white', 9.2, { float: 1, st: 1, desc: '冷门步枪，涨跌主要靠大盘带动。' }],
  ['sg553-danger', 'SG 553 | 危险距离', '步枪', 'white', 10.5, { float: 1, st: 1, desc: '低价位里少数有图案溢价的皮肤。' }],
  ['ssg08-blood', 'SSG 08 | 血腥之网', '狙击枪', 'white', 11.8, { float: 1, st: 1, desc: '开箱副产物，价格贴近底价。' }],
  ['nova-toy', 'Nova | 玩具士兵', '霰弹枪', 'white', 12.6, { float: 1, st: 1, desc: '主题设计带来小幅收藏需求。' }],
  ['p250-valence', 'P250 | 化合价', '手枪', 'white', 13.5, { float: 1, st: 1, desc: 'P250 系列里较受欢迎的入门款。' }],
  ['mp9-nuclear', 'MP9 | 核子危机', '微型冲锋枪', 'white', 14.8, { float: 1, st: 1, desc: '地图收藏需求支撑的稳定标的。' }],
  ['mac10-pipe', 'MAC-10 | 管道', '微型冲锋枪', 'white', 16.2, { float: 1, st: 1, desc: '低端市场中换手最快的一类。' }],
  ['glock-weasel', 'Glock-18 | 黄鼬', '手枪', 'white', 17.5, { float: 1, st: 1, desc: '图案风格讨喜，长期缓慢升值。' }],
  // 绿 —— 军规级
  ['ak47-emerald', 'AK-47 | 翡翠之纹', '步枪', 'green', 19.5, { float: 1, st: 1, desc: '军规级 AK，成交主力，价格跟随大盘。' }],
  ['m4a4-desert', 'M4A4 | 沙漠风暴', '步枪', 'green', 21, { float: 1, st: 1, desc: '老牌军规皮肤，供给稳定。' }],
  ['awp-pit', 'AWP | 深渊之坑', '狙击枪', 'green', 23.5, { float: 1, st: 1, desc: '低价位 AWP，新手升级首选之一。' }],
  ['usp-torque', 'USP-S | 扭矩', '手枪', 'green', 26, { float: 1, st: 1, desc: '军规级手枪，因枪型主流而流动性好。' }],
  ['glock-water', 'Glock-18 | 水元素', '手枪', 'green', 28.5, { float: 1, st: 1, desc: '图案清爽，价格随开箱量波动。' }],
  ['m4a1s-basilisk', 'M4A1-S | 蛇怪', '步枪', 'green', 31, { float: 1, st: 1, desc: '低端步枪皮的常见配置，回收顺畅。' }],
  ['p250-asimov', 'P250 | 二西莫夫', '手枪', 'green', 33.5, { float: 1, st: 1, desc: '二西莫夫系列的入门款，整条产品线联动涨跌。' }],
  ['famas-mecha', 'FAMAS | 机甲工业', '步枪', 'green', 36, { float: 1, st: 1, desc: '冷门枪型中的热门皮肤，反而有溢价。' }],
  ['galil-ar-modern', 'Galil AR | 现代猎手', '步枪', 'green', 39, { float: 1, st: 1, desc: '价格随综合图案系列一起波动。' }],
  ['sg553-colony', 'SG 553 | 殖民地', '步枪', 'green', 42, { float: 1, st: 1, desc: '冷门但不缺买家，价格平稳。' }],
  ['aug-torque', 'AUG | 扭矩', '步枪', 'green', 45, { float: 1, st: 1, desc: '与主流图案系列同涨同跌。' }],
  ['mp9-bulldozer', 'MP9 | 推土机', '微型冲锋枪', 'green', 48, { float: 1, st: 1, desc: '老箱子皮肤，随停落缓慢上行。' }],
  ['mp7-impire', 'MP7 | 装甲核心', '微型冲锋枪', 'green', 52, { float: 1, st: 1, desc: '军规级冲锋枪，成交量一般。' }],
  ['mac10-neon', 'MAC-10 | 霓虹骑士', '微型冲锋枪', 'green', 56, { float: 1, st: 1, desc: '夜光风格，年轻玩家偏好明显。' }],
  ['ump45-primal', 'UMP-45 | 原始人', '微型冲锋枪', 'green', 60, { float: 1, st: 1, desc: '图案辨识度高，价格有韧性。' }],
  ['p90-trigon', 'P90 | 三角', '微型冲锋枪', 'green', 65, { float: 1, st: 1, desc: '老皮肤，价位长期稳定。' }],
  ['deagle-lightning', 'Desert Eagle | 闪电', '手枪', 'green', 70, { float: 1, st: 1, desc: '沙鹰中端款，需求稳定。' }],
  ['fiveseven-monkey', 'Five-SeveN | 猴子生意', '手枪', 'green', 75, { float: 1, st: 1, desc: '趣味设计，偶有短期炒作。' }],
  ['tec9-bamboo', 'Tec-9 | 竹影', '手枪', 'green', 80, { float: 1, st: 1, desc: '主题系列中的低价位。' }],
  ['cz75-emerald', 'CZ75-Auto | 翡翠', '手枪', 'green', 86, { float: 1, st: 1, desc: '冷门枪型，价格易被单笔大单推动。' }],
  ['ssg08-bigiron', 'SSG 08 | 大铁', '狙击枪', 'green', 92, { float: 1, st: 1, desc: '低价位狙击皮，成交零散。' }],
  ['aug-chameleon', 'AUG | 变色龙', '步枪', 'green', 98, { float: 1, st: 1, desc: '军规级中较热门的选择。' }],
  ['xm1014-quicksilver', 'XM1014 | 水银', '霰弹枪', 'green', 105, { float: 1, st: 1, desc: '霰弹枪里少见的稳定标的。' }],
  ['m249-jungle', 'M249 | 丛林迷彩', '机枪', 'green', 112, { float: 1, st: 1, desc: '机枪皮肤，流动性差导致折价明显。' }],
  ['negev-manowar', 'Negev | 蛮族', '机枪', 'green', 120, { float: 1, st: 1, desc: '冷门但价格抗跌，供给有限。' }],
  ['usp-stainless', 'USP-S | 不锈钢', '手枪', 'green', 128, { float: 1, st: 1, desc: '经典款，长期缓慢升值。' }],
  ['glock-grinder', 'Glock-18 | 研磨者', '手枪', 'green', 137, { float: 1, st: 1, desc: '格子风格，价格随主题系列波动。' }],
  ['p2000-fire', 'P2000 | 火元素', '手枪', 'green', 146, { float: 1, st: 1, desc: '老皮肤，靠停落上行。' }],
  ['sawedoff-serenity', 'Sawed-Off | 宁静', '霰弹枪', 'green', 156, { float: 1, st: 1, desc: '设计独特，收藏盘稳定。' }],
  ['mag7-hazard', 'MAG-7 | 危险品', '霰弹枪', 'green', 166, { float: 1, st: 1, desc: '工业主题，价格平稳。' }],
  ['nova-antique', 'Nova | 古铜', '霰弹枪', 'green', 176, { float: 1, st: 1, desc: '低端中的质感款，成交活跃度中低。' }],
  ['m4a4-tornado', 'M4A4 | 龙卷风', '步枪', 'green', 188, { float: 1, st: 1, desc: '军规级 M4，随步枪大盘波动。' }],
  ['ak47-safari', 'AK-47 | 丛林迷彩', '步枪', 'green', 199, { float: 1, st: 1, desc: 'AK 军规级，是低价 AK 的代表。' }],
  ['awp-wormgod', 'AWP | 虫神', '狙击枪', 'green', 212, { float: 1, st: 1, desc: '狙击皮中间价位，成交频繁。' }],
  ['galil-cerberus2', 'Galil AR | 三头犬', '步枪', 'green', 226, { float: 1, st: 1, desc: '军规级里图案较讲究的一款。' }],
  ['famas-rollcage', 'FAMAS | 防滚架', '步枪', 'green', 240, { float: 1, st: 1, desc: '冷门枪型，价格靠供给支撑。' }],
  ['sg553-cyrex', 'SG 553 | 赛博安全', '步枪', 'green', 255, { float: 1, st: 1, desc: '赛博系列低价位，随系列联动。' }],
  ['ump45-lab', 'UMP-45 | 实验室', '微型冲锋枪', 'green', 270, { float: 1, st: 1, desc: '地图主题，价格小幅波动。' }],
  ['mp9-hydra', 'MP9 | 九头蛇', '微型冲锋枪', 'green', 286, { float: 1, st: 1, desc: '大行动皮肤，供给有限。' }],
  ['mac10-curse', 'MAC-10 | 诅咒', '微型冲锋枪', 'green', 302, { float: 1, st: 1, desc: '军规级中人气款，流动性尚可。' }],
  ['ppbizon-judge', 'PP-巴拉克拉瓦 | 审判者', '微型冲锋枪', 'green', 320, { float: 1, st: 1, desc: '冷门枪型，价格易被单笔订单影响。' }],
  ['p90-elite', 'P90 | 精英之作', '微型冲锋枪', 'green', 338, { float: 1, st: 1, desc: '经典图案，长期持有价值稳定。' }],
  ['cz75-xiangliu', 'CZ75-Auto | 相柳', '手枪', 'green', 356, { float: 1, st: 1, desc: '国风主题，短期炒作较多。' }],
  ['tec9-fubar', 'Tec-9 | 故障艺术', '手枪', 'green', 375, { float: 1, st: 1, desc: '创意设计，年轻市场偏好。' }],
  ['deagle-mecha', 'Desert Eagle | 机甲工业', '手枪', 'green', 395, { float: 1, st: 1, desc: '沙鹰军规级，随枪型热度起伏。' }],
  ['fiveseven-case', 'Five-SeveN | 硬核回收', '手枪', 'green', 415, { float: 1, st: 1, desc: '冷门枪型的军规皮肤。' }],
  ['r8-fade', 'R8 左轮 | 渐变色', '手枪', 'green', 436, { float: 1, st: 1, desc: '渐变色系列在 R8 上的入门款。' }],
  ['elites-moon', '双持贝瑞塔 | 月神', '手枪', 'green', 458, { float: 1, st: 1, desc: '设计感强，收藏盘稳定。' }],
  ['m4a1s-guardian', 'M4A1-S | 守护者', '步枪', 'green', 480, { float: 1, st: 1, desc: '军规级步枪，成交活跃。' }],
  ['ak47-blue-laminate', 'AK-47 | 蓝色层压板', '步枪', 'green', 505, { float: 1, st: 1, desc: '经典款，价格随 AK 大盘走。' }],
  ['awp-corticera', 'AWP | 树蝰', '狙击枪', 'green', 530, { float: 1, st: 1, desc: '军规级狙击，供给稳定。' }],
  // 蓝 —— 受限级
  ['m4a4-black-mirage', 'M4A4 | 黑色魅影', '步枪', 'blue', 300, { float: 1, st: 1, desc: '经久耐看的黑色系，久经沙场成交量极大。' }],
  ['ak47-redline', 'AK-47 | 红线', '步枪', 'blue', 128, { float: 1, st: 1, desc: 'AK 红线是流通性最好的受限级皮肤之一。' }],
  ['awp-undead', 'AWP | 亡灵之主', '狙击枪', 'blue', 33, { float: 1, st: 1, desc: '低价位 AWP，开箱池主力掉落之一。' }],
  ['m4a1s-cyrex', 'M4A1-S | 赛博安全', '步枪', 'blue', 168, { float: 1, st: 1, desc: '赛博系列核心款，随系列同涨同跌。' }],
  ['ak47-fuel-injector', 'AK-47 | 燃料喷射器', '步枪', 'blue', 6999, { float: 1, st: 1, desc: '受限级中的高价异类，供给稀少，长期看涨。' }],
  ['m4a4-asimov', 'M4A4 | 二西莫夫', '步枪', 'blue', 470, { float: 1, st: 1, desc: '二西莫夫系列标志款，需求长期稳定。' }],
  ['glock-fade', 'Glock-18 | 渐变之色', '手枪', 'blue', 1180, { float: 1, st: 1, desc: '渐变色的入门款，模板差异带来价格分层。' }],
  ['usp-kill-confirmed', 'USP-S | 枪响人亡', '手枪', 'blue', 320, { float: 1, st: 1, desc: '热门手枪皮肤，交易频繁。' }],
  ['deagle-code-red', 'Desert Eagle | 代号红色', '手枪', 'blue', 560, { float: 1, st: 1, desc: '沙鹰受限级，随枪型热度波动。' }],
  ['p250-undead', 'P250 | 亡灵之主', '手枪', 'blue', 42, { float: 1, st: 1, desc: '低价受限级，换手快但溢价有限。' }],
  ['awp-lightning', 'AWP | 雷击', '狙击枪', 'blue', 1450, { float: 1, st: 1, desc: '经典电击图案，供给偏紧。' }],
  ['awp-electric-hive', 'AWP | 电子蜂巢', '狙击枪', 'blue', 860, { float: 1, st: 1, desc: '色彩鲜明，收藏需求稳定。' }],
  ['m4a4-neon', 'M4A4 | 霓虹革命', '步枪', 'blue', 640, { float: 1, st: 1, desc: '霓虹系列，价格随赛事热度波动。' }],
  ['ak47-point', 'AK-47 | 点将台', '步枪', 'blue', 380, { float: 1, st: 1, desc: '国风主题，亚洲盘需求较高。' }],
  ['ak47-jaguar', 'AK-47 | 美洲豹', '步枪', 'blue', 520, { float: 1, st: 1, desc: '受限级 AK，图案辨识度高。' }],
  ['m4a1s-printstream', 'M4A1-S | 印花集', '步枪', 'blue', 3100, { float: 1, st: 1, desc: '印花集是近两年最受欢迎的设计之一，价格坚挺。' }],
  ['mp9-starlight', 'MP9 | 星光', '微型冲锋枪', 'blue', 190, { float: 1, st: 1, desc: '冲锋枪中的热门款，价格波动温和。' }],
  ['mac10-disco', 'MAC-10 | 迪斯科', '微型冲锋枪', 'blue', 210, { float: 1, st: 1, desc: '复古主题，年轻玩家偏好。' }],
  ['mp7-nemesis', 'MP7 | 复仇者', '微型冲锋枪', 'blue', 240, { float: 1, st: 1, desc: '经典受限级，价格抗跌。' }],
  ['ump45-momentum', 'UMP-45 | 动能', '微型冲锋枪', 'blue', 175, { float: 1, st: 1, desc: '设计现代，成交活跃度中高。' }],
  ['p90-asiimov', 'P90 | 二西莫夫', '微型冲锋枪', 'blue', 700, { float: 1, st: 1, desc: '二西莫夫系列在 P90 上的表现最抢眼。' }],
  ['famas-afterimage', 'FAMAS | 残影', '步枪', 'blue', 260, { float: 1, st: 1, desc: '冷门枪型的受限级，靠供给支撑。' }],
  ['galil-sugar', 'Galil AR | 糖果苹果', '步枪', 'blue', 230, { float: 1, st: 1, desc: '活泼配色，价格随系列波动。' }],
  ['aug-symphony', 'AUG | 交响乐', '步枪', 'blue', 285, { float: 1, st: 1, desc: '图案精致，收藏盘稳定。' }],
  ['sg553-damascus', 'SG 553 | 大马士革钢', '步枪', 'blue', 305, { float: 1, st: 1, desc: '金属质感，随大马士革系列联动。' }],
  ['ssg08-detour', 'SSG 08 | 迂回', '狙击枪', 'blue', 155, { float: 1, st: 1, desc: '低价狙击皮，成交零散但折价小。' }],
  ['cz75-victoria', 'CZ75-Auto | 维多利亚', '手枪', 'blue', 340, { float: 1, st: 1, desc: '复古款，供给有限。' }],
  ['fiveseven-fowl', 'Five-SeveN | 家禽', '手枪', 'blue', 205, { float: 1, st: 1, desc: '趣味图案，偶有短期拉升。' }],
  ['tec9-remote', 'Tec-9 | 遥控器', '手枪', 'blue', 225, { float: 1, st: 1, desc: '冷门但价格平稳。' }],
  ['elites-deck', '双持贝瑞塔 | 甲板', '手枪', 'blue', 180, { float: 1, st: 1, desc: '低调设计，成交靠批量。' }],
  ['xm1014-tranquility', 'XM1014 | 宁静之海', '霰弹枪', 'blue', 195, { float: 1, st: 1, desc: '霰弹枪中的高人气，流动性好于同类。' }],
  ['mag7-justice', 'MAG-7 | 正义', '霰弹枪', 'blue', 165, { float: 1, st: 1, desc: '价格随主题系列小幅波动。' }],
  ['nova-hyper', 'Nova | 超新星', '霰弹枪', 'blue', 150, { float: 1, st: 1, desc: '冷门枪型，折价常年存在。' }],
  ['sawedoff-kiss', 'Sawed-Off | 真爱如血', '霰弹枪', 'blue', 185, { float: 1, st: 1, desc: '主题鲜明，收藏需求稳定。' }],
  ['m249-hurricane', 'M249 | 飓风', '机枪', 'blue', 220, { float: 1, st: 1, desc: '机枪里较受欢迎的款式，流动性仍偏弱。' }],
  ['negev-power', 'Negev | 电源', '机枪', 'blue', 200, { float: 1, st: 1, desc: '冷门枪型，价格靠供给。' }],
  ['p2000-handgun', 'P2000 | 手炮', '手枪', 'blue', 170, { float: 1, st: 1, desc: '受限级手枪，成交清淡。' }],
  ['r8-survival', 'R8 左轮 | 生存主义', '手枪', 'blue', 160, { float: 1, st: 1, desc: '冷门左轮，价格易被单笔推动。' }],
  ['m4a4-zirka', 'M4A4 | 锯齿', '步枪', 'blue', 420, { float: 1, st: 1, desc: '受限级 M4，随步枪大盘。' }],
  ['awp-wildfire', 'AWP | 野火', '狙击枪', 'blue', 2600, { float: 1, st: 1, desc: '经典野火图案，长期需求稳定。' }],
  ['ak47-emerald2', 'AK-47 | 翡翠之纹 (暗金)', '步枪', 'blue', 245, { float: 1, st: 1, desc: '受限级 AK 的常见配置，流通量大。' }],
  ['m4a1s-golden', 'M4A1-S | 黄金藤蔓', '步枪', 'blue', 1350, { float: 1, st: 1, desc: '贵金属设计，随黄金系列联动。' }],
  ['ak47-slate', 'AK-47 | 石板', '步枪', 'blue', 290, { float: 1, st: 1, desc: '低调配色，长期持有稳定。' }],
  ['glock-weasel2', 'Glock-18 | 水灵', '手枪', 'blue', 420, { float: 1, st: 1, desc: '灵感清透，亚洲盘偏好明显。' }],
  ['usp-blue-phosphor', 'USP-S | 蓝色磷光', '手枪', 'blue', 1290, { float: 1, st: 1, desc: 'USP 高端设计，价格坚挺。' }],
  ['m4a4-desolate', 'M4A4 | 荒芜之地', '步枪', 'blue', 350, { float: 1, st: 1, desc: '军旅主题，成交量稳定。' }],
  ['awp-asiimov', 'AWP | 二西莫夫', '狙击枪', 'blue', 980, { float: 1, st: 1, desc: '二西莫夫系列的旗舰款之一，需求常年旺盛。' }],
  ['ak47-case-hardened', 'AK-47 | 表面淬火', '步枪', 'blue', 1750, { float: 1, st: 1, desc: '模板决定价格，蓝色比例越高溢价越夸张。' }],
  ['awp-boom', 'AWP | 黑色魅影', '狙击枪', 'blue', 1180, { float: 1, st: 1, desc: '狙击手常用，成交活跃。' }],
  ['m4a1s-hot-rod', 'M4A1-S | 热熔', '步枪', 'blue', 760, { float: 1, st: 1, desc: '配色大胆，随赛事周期波动。' }],
  ['mp9-food', 'MP9 | 食物链', '微型冲锋枪', 'blue', 165, { float: 1, st: 1, desc: '冷门但价格抗跌。' }],
  ['mac10-neon2', 'MAC-10 | 霓虹骑士 (暗金)', '微型冲锋枪', 'blue', 158, { float: 1, st: 1, desc: '暗金版本带来额外溢价。' }],
  ['ak47-blood', 'AK-47 | 血腥运动', '步枪', 'blue', 460, { float: 1, st: 1, desc: '血腥运动系列人气款，换手率高。' }],
  ['deagle-printstream', 'Desert Eagle | 印花集', '手枪', 'blue', 4200, { float: 1, st: 1, desc: '印花集沙鹰，是收藏级别的高价受限皮肤。' }],
  ['ak47-nightwish', 'AK-47 | 夜愿', '步枪', 'blue', 260, { float: 1, st: 1, desc: '金属质感，随图案系列波动。' }],
  ['m4a4-charter', 'M4A4 | 图纸', '步枪', 'blue', 330, { float: 1, st: 1, desc: '工程风格，价格平稳。' }],
  ['awp-containment', 'AWP | 封锁', '狙击枪', 'blue', 720, { float: 1, st: 1, desc: '地图主题，供需两旺。' }],
  ['glock-moonrise', 'Glock-18 | 月升', '手枪', 'blue', 480, { float: 1, st: 1, desc: '设计讨喜，价格有韧性。' }],
  ['usp-cortex', 'USP-S | 皮层', '手枪', 'blue', 340, { float: 1, st: 1, desc: '解剖主题，成交稳定。' }],
  ['ak47-asiimov', 'AK-47 | 二西莫夫', '步枪', 'blue', 1150, { float: 1, st: 1, desc: '二西莫夫 AK，需求长期旺盛。' }],
  ['m4a1s-master', 'M4A1-S | 大师碎片', '步枪', 'blue', 560, { float: 1, st: 1, desc: '碎片主题系列，随系列联动。' }],
  ['mp9-starlight2', 'MP9 | 星尘', '微型冲锋枪', 'blue', 175, { float: 1, st: 1, desc: '低价位受限级，流动性好。' }],
  ['awp-neo-noir', 'AWP | 黑色魅影 (暗金)', '狙击枪', 'blue', 1420, { float: 1, st: 1, desc: '暗金版本，收藏与实用双重需求。' }],
  ['ak47-head-shot', 'AK-47 | 爆头', '步枪', 'blue', 390, { float: 1, st: 1, desc: '涂鸦风格，年轻玩家偏好。' }],
  ['m4a4-magnesium', 'M4A4 | 镁元素', '步枪', 'blue', 355, { float: 1, st: 1, desc: '工业风，价格随大盘。' }],
  ['tec9-brass', 'Tec-9 | 黄铜', '手枪', 'blue', 148, { float: 1, st: 1, desc: '冷门枪型，折价明显。' }],
  ['galil-chromatic', 'Galil AR | 虹彩', '步枪', 'blue', 215, { float: 1, st: 1, desc: '冷门枪型里较受欢迎的一款。' }],
  ['awp-fade', 'AWP | 渐变色', '狙击枪', 'blue', 5400, { float: 1, st: 1, desc: '渐变色 AWP，模板差异带来巨大价格分层。' }],
  // 紫 —— 保密级
  ['ak47-vulcan', 'AK-47 | 火神', '步枪', 'purple', 3200, { float: 1, st: 1, desc: '火神是 AK 保密级的标杆，需求常年旺盛。' }],
  ['ak47-asiimov2', 'AK-47 | 火神 (StatTrak)', '步枪', 'purple', 8600, { float: 1, st: 1, desc: '暗金火神，计数记录带来额外溢价。' }],
  ['m4a4-horus', 'M4A4 | 荷鲁斯之眼', '步枪', 'purple', 8199, { float: 1, st: 1, desc: '古埃及主题旗舰设计，供给稀少。' }],
  ['m4a1s-hyper-beast', 'M4A1-S | 暴怒野兽', '步枪', 'purple', 1600, { float: 1, st: 1, desc: '暴怒野兽系列核心款，赛事期间波动明显。' }],
  ['awp-prince', 'AWP | 王子', '狙击枪', 'purple', 12300, { float: 1, st: 1, desc: '王子是最贵的常规 AWP 皮肤之一，长期看涨。' }],
  ['awp-asiimov1', 'AWP | 传承', '狙击枪', 'purple', 42000, { float: 1, st: 1, desc: '传承系列旗舰，长期被视作收藏级标杆，价格坚挺。' }],
  ['ak47-wasteland', 'AK-47 | 荒野反叛', '步枪', 'purple', 2100, { float: 1, st: 1, desc: '废土主题，玩家偏好稳定。' }],
  ['ak47-neon-rider', 'AK-47 | 霓虹骑士', '步枪', 'purple', 1750, { float: 1, st: 1, desc: '霓虹骑士系列旗舰，价格随赛事热度。' }],
  ['m4a4-the-empress', 'M4A4 | 皇后', '步枪', 'purple', 2400, { float: 1, st: 1, desc: '华丽的皇室设计，收藏需求稳定。' }],
  ['m4a4-royal', 'M4A4 | 皇家圣骑士', '步枪', 'purple', 1300, { float: 1, st: 1, desc: '古典风格，成交活跃。' }],
  ['awp-asiimov3', 'AWP | 巨龙传说 (StatTrak)', '狙击枪', 'purple', 96000, { float: 1, st: 1, desc: '暗金巨龙传说，属于极少数人会真正持有的标的。' }],
  ['awp-forest-ddp', 'AWP | 二西莫夫 (StatTrak)', '狙击枪', 'purple', 4800, { float: 1, st: 1, desc: '暗金二西莫夫 AWP，需求稳定。' }],
  ['usp-printstream', 'USP-S | 印花集', '手枪', 'purple', 4600, { float: 1, st: 1, desc: '印花集 USP，是手枪里最贵的常见款。' }],
  ['glock-printstream', 'Glock-18 | 印花集', '手枪', 'purple', 1900, { float: 1, st: 1, desc: '印花集系列，价格随系列整体走。' }],
  ['deagle-blaze', 'Desert Eagle | 烈焰之炬', '手枪', 'purple', 2800, { float: 1, st: 1, desc: '烈焰图案经典，模板差异明显。' }],
  ['deagle-printstream2', 'Desert Eagle | 印花集 (StatTrak)', '手枪', 'purple', 9800, { float: 1, st: 1, desc: '暗金印花集沙鹰，收藏级标的。' }],
  ['ak47-fire-serpent', 'AK-47 | 火蛇', '步枪', 'purple', 34000, { float: 1, st: 1, desc: '火蛇是 AK 系最贵的经典款，供给极稀。' }],
  ['m4a1s-printstream2', 'M4A1-S | 印花集 (StatTrak)', '步枪', 'purple', 7800, { float: 1, st: 1, desc: '暗金印花集 M4A1-S，需求长期旺盛。' }],
  ['awp-chromatic', 'AWP | 二西莫夫 (暗金)', '狙击枪', 'purple', 3600, { float: 1, st: 1, desc: '常青款，价格跟随大盘。' }],
  ['ak47-jaguar2', 'AK-47 | 美洲豹 (StatTrak)', '步枪', 'purple', 2600, { float: 1, st: 1, desc: '暗金美洲豹，成交活跃。' }],
  ['m4a4-asiimov2', 'M4A4 | 二西莫夫 (StatTrak)', '步枪', 'purple', 3100, { float: 1, st: 1, desc: '暗金二西莫夫 M4A4，主流收藏标的。' }],
  ['ak47-blood2', 'AK-47 | 血腥运动 (StatTrak)', '步枪', 'purple', 2200, { float: 1, st: 1, desc: '暗金血腥运动，换手率高。' }],
  ['m4a1s-golden2', 'M4A1-S | 黄金藤蔓 (StatTrak)', '步枪', 'purple', 6200, { float: 1, st: 1, desc: '暗金黄金藤蔓，黄金系列旗舰。' }],
  ['awp-lightning2', 'AWP | 雷击 (StatTrak)', '狙击枪', 'purple', 5600, { float: 1, st: 1, desc: '暗金雷击，供给偏紧。' }],
  ['usp-kill2', 'USP-S | 枪响人亡 (StatTrak)', '手枪', 'purple', 1450, { float: 1, st: 1, desc: '暗金版，需求稳定。' }],
  ['ak47-cyclop', 'AK-47 | 独眼巨人', '步枪', 'purple', 1450, { float: 1, st: 1, desc: '神话主题，价格随主题系列联动。' }],
  ['m4a4-moonrise', 'M4A4 | 月升', '步枪', 'purple', 1100, { float: 1, st: 1, desc: '夜主题设计，收藏盘稳定。' }],
  ['awp-mortis', 'AWP | 死神', '狙击枪', 'purple', 2200, { float: 1, st: 1, desc: '骷髅主题，需求有周期性。' }],
  ['ak47-legion', 'AK-47 | 军团', '步枪', 'purple', 1680, { float: 1, st: 1, desc: '军事主题，随大盘波动。' }],
  ['m4a1s-blue-phosphor', 'M4A1-S | 蓝色磷光', '步枪', 'purple', 1350, { float: 1, st: 1, desc: '清透配色，亚洲盘偏好。' }],
  ['awp-wildfire2', 'AWP | 野火 (StatTrak)', '狙击枪', 'purple', 4700, { float: 1, st: 1, desc: '暗金野火，长期需求稳定。' }],
  ['ak47-the-empress', 'AK-47 | 皇后', '步枪', 'purple', 3300, { float: 1, st: 1, desc: '皇室主题，价格抗跌。' }],
  ['m4a4-hyper', 'M4A4 | 暴怒野兽', '步枪', 'purple', 2900, { float: 1, st: 1, desc: '暴怒野兽 M4A4，赛事期间需求上升。' }],
  ['awp-atheris', 'AWP | 天神', '狙击枪', 'purple', 5600, { float: 1, st: 1, desc: '神话旗舰，供给有限。' }],
  ['ak47-asiimov3', 'AK-47 | 二西莫夫 (StatTrak)', '步枪', 'purple', 2900, { float: 1, st: 1, desc: '暗金二西莫夫 AK，换手活跃。' }],
  ['deagle-code-red2', 'Desert Eagle | 代号红色 (StatTrak)', '手枪', 'purple', 2400, { float: 1, st: 1, desc: '暗金沙鹰，需求稳定。' }],
  ['ak47-emerald-pinstripe', 'AK-47 | 翡翠条纹', '步枪', 'purple', 1900, { float: 1, st: 1, desc: '贵金属质感，价格坚挺。' }],
  ['m4a1s-hot-rod2', 'M4A1-S | 热熔 (StatTrak)', '步枪', 'purple', 2650, { float: 1, st: 1, desc: '暗金热熔，赛事周期带动明显。' }],
  ['awp-containment2', 'AWP | 封锁 (StatTrak)', '狙击枪', 'purple', 2950, { float: 1, st: 1, desc: '暗金封锁，供给偏紧。' }],
  ['ak47-slate2', 'AK-47 | 石板 (StatTrak)', '步枪', 'purple', 1250, { float: 1, st: 1, desc: '暗金石板，低调但成交稳定。' }],
  // 金 —— 隐秘级
  ['ak47-xray', 'AK-47 | X射线', '步枪', 'gold', 16680, { float: 1, st: 1, desc: 'X射线是隐秘级里的高价常客，供给稀少。' }],
  ['ak47-hydroponic', 'AK-47 | 水栽竹', '步枪', 'gold', 28970, { float: 1, st: 1, desc: '水栽竹因稀有与颜值双重属性长期高位。' }],
  ['m4a4-howling', 'M4A4 | 咆哮', '步枪', 'gold', 44899, { float: 1, st: 1, desc: '咆哮是最著名的受限供应皮肤，价格极具韧性。' }],
  ['awp-dragon-lore', 'AWP | 巨龙传说', '狙击枪', 'gold', 80500, { float: 1, st: 1, desc: '巨龙传说是狙击皮肤的顶级标的，波动温和但昂贵。' }],
  ['awp-medusa', 'AWP | 美杜莎', '狙击枪', 'gold', 39800, { float: 1, st: 1, desc: '美杜莎供给稀缺，价格长期上行。' }],
  ['m4a4-howl2', 'M4A4 | 咆哮 (StatTrak)', '步枪', 'gold', 128000, { float: 1, st: 1, desc: '暗金咆哮属于极稀缺标的，成交寡淡但价格坚挺。' }],
  ['ak47-fire-serpent2', 'AK-47 | 火蛇 (StatTrak)', '步枪', 'gold', 78000, { float: 1, st: 1, desc: '暗金火蛇，顶级收藏标的之一。' }],
  ['awp-dragon-lore2', 'AWP | 巨龙传说 (暗金)', '狙击枪', 'gold', 165000, { float: 1, st: 1, desc: '暗金巨龙传说，成交量极少，价格由极少数人决定。' }],
  ['m4a1s-printstream3', 'M4A1-S | 印花集 (纪念品)', '步枪', 'gold', 26000, { float: 1, st: 0, desc: '纪念品版本带有赛事贴纸，收藏属性拉满。' }],
  ['ak47-wild-lotus', 'AK-47 | 野荷', '步枪', 'gold', 21500, { float: 1, st: 1, desc: '野荷设计精美，是近年最受欢迎的隐秘级之一。' }],
  ['awp-gungnir', 'AWP | 永恒之枪', '狙击枪', 'gold', 88000, { float: 1, st: 1, desc: '北欧神话题材旗舰，供给极稀。' }],
  ['m4a1s-master2', 'M4A1-S | 大师碎片 (StatTrak)', '步枪', 'gold', 9800, { float: 1, st: 1, desc: '暗金大师碎片，价格随系列整体走。' }],
  ['ak47-gold-arabesque', 'AK-47 | 黄金藤蔓', '步枪', 'gold', 12300, { float: 1, st: 1, desc: '黄金主题，亚洲盘需求强劲。' }],
  ['m4a4-asimov3', 'M4A4 | 二西莫夫 (纪念品)', '步枪', 'gold', 12800, { float: 1, st: 0, desc: '纪念品二西莫夫，贴纸组合决定溢价。' }],
  ['ak47-case-hardened2', 'AK-47 | 表面淬火 (蓝宝石模板)', '步枪', 'gold', 168000, { float: 1, st: 1, pattern: '蓝宝石 Pattern 661', desc: '蓝宝石模板 661 是淬火系列的顶点，模板决定一切。' }],
  ['awp-black-nile', 'AWP | 黑尼罗河', '狙击枪', 'gold', 34500, { float: 1, st: 1, desc: '古埃及系列旗舰，价格坚挺。' }],
  // 红 —— 罕见 / 刀 / 手套
  ['butterfly-doppler-ruby', '★ 蝴蝶刀 | 多普勒 红宝石', '刀', 'red', 98500, { float: 1, st: 1, pattern: '多普勒 红宝石', desc: '红宝石多普勒蝴蝶刀，出货即上头条，短期易被拉涨。' }],
  ['butterfly-crimson-web', '★ 蝴蝶刀 | 深红之网', '刀', 'red', 136000, { float: 1, st: 1, pattern: '完美模板', desc: '深红之网模板差异极大，完美网价格高出一档。' }],
  ['butterfly-marble-fade', '★ 蝴蝶刀 | 渐变大理石', '刀', 'red', 38500, { float: 1, st: 1, pattern: '火与冰', desc: '渐变大理石蝴蝶刀，火与冰模板溢价明显。' }],
  ['karambit-case-hardened-blue', '★ Karambit | 淬火 (蓝宝石 Pattern)', '刀', 'red', 400000, { float: 1, st: 1, pattern: '蓝宝石 Pattern 661', desc: '爪子刀蓝宝石淬火是饰品界的天花板之一，可遇不可求。' }],
  ['karambit-doppler-ruby', '★ Karambit | 多普勒 红宝石', '刀', 'red', 172000, { float: 1, st: 1, pattern: '多普勒 红宝石', desc: '红宝石爪子刀，价格长期位居前三。' }],
  ['m9-doppler-ruby', '★ M9刺刀 | 多普勒 红宝石', '刀', 'red', 70200, { float: 1, st: 1, pattern: '多普勒 红宝石', desc: '红宝石 M9，是高端盘中成交量较大的品种。' }],
  ['karambit-fade', '★ Karambit | 渐变之色', '刀', 'red', 52000, { float: 1, st: 1, pattern: '渐变之色', desc: '渐变百分比决定价格，接近 100% 的极难寻。' }],
  ['butterfly-slaughter', '★ 蝴蝶刀 | 屠夫', '刀', 'red', 46000, { float: 1, st: 1, pattern: '钻石/天使', desc: '屠夫图案中钻石与天使模板溢价最高。' }],
  ['karambit-tiger-tooth', '★ Karambit | 虎牙', '刀', 'red', 89000, { float: 1, st: 1, desc: '虎牙是经典高端刀皮，价格极其坚挺。' }],
  ['sport-gloves-pandora', '★ 运动手套 | 潘多拉之盒', '手套', 'red', 43800, { float: 1, st: 0, desc: '潘多拉之盒是手套中的顶级配色，久经沙场即可定价数万。' }],
  // 影响波动率标记的少数单品
  ['awp-dragon-lore-lore', 'AWP | 巨龙传说（纪念品 FN）', '狙击枪', 'red', 285000, { float: 1, st: 0, desc: '纪念品巨龙传说，赛事贴纸让它成为传奇标的。' }],
);

/* =========================== AI 算力 (90) =========================== */
W(COMPUTE,
  ['c-p106-100', 'NVIDIA P106-100 6GB 矿卡', 'GPU', 'white', 320, { desc: '专用挖矿卡，无显示输出，二手市场充斥。' }],
  ['c-p104-100', 'NVIDIA P104-100 8GB 矿卡', 'GPU', 'white', 420, { desc: '矿潮遗物，价格随加密行情波动。' }],
  ['c-cmp-30hx', 'NVIDIA CMP 30HX 矿卡', 'GPU', 'white', 560, { desc: '官方矿卡，无保修，回收价极低。' }],
  ['c-rx470-8g', 'AMD RX 470 8GB 矿卡', 'GPU', 'white', 260, { desc: '老矿卡，价格见底后长期横盘。' }],
  ['c-token-trial', '推理 API 体验包 100万 Token', '模型Token', 'white', 5, { desc: '小额体验额度，随厂商促销频繁贬值。' }],
  ['c-token-cheap', '国产轻量模型 500万 Token 包', '模型Token', 'white', 22, { desc: '低价推理额度，价格随平台补贴波动。' }],
  ['c-token-embed', '向量嵌入 1亿 Token 包', '模型Token', 'white', 40, { desc: '用于检索增强的嵌入额度，单价极低。' }],
  ['c-token-asr', '语音转写 1000小时 额度包', '模型Token', 'white', 78, { desc: '语音识别额度，价格随算力成本下行。' }],
  ['c-token-tts', '语音合成 500万字符 包', '模型Token', 'white', 95, { desc: 'TTS 字符包，竞争激烈导致持续降价。' }],
  ['c-rent-4090-hour', 'RTX 4090 单卡时租', '算力租赁', 'white', 12, { desc: '按卡时计费的个人算力租赁，供给弹性大。' }],
  ['c-dataset-toy', '公开小样本数据集 1万条', '数据集', 'white', 30, { desc: '公开可得的标注样本，几乎没有稀缺性。' }],
  ['c-lora-style', 'LoRA 风格包 单风格', '算法模型', 'white', 180, { desc: '轻量微调权重，作者众多导致价格偏低。' }],
  ['c-tesla-t4', 'NVIDIA Tesla T4 16GB', 'AI算力卡', 'green', 1450, { desc: '上一代推理卡，性价比高但已逐步退役。' }],
  ['c-tesla-p40', 'NVIDIA Tesla P40 24GB', 'AI算力卡', 'green', 980, { desc: '大显存老卡，适合本地推理但无新驱动支持。' }],
  ['c-v100-16g', 'NVIDIA Tesla V100 16GB', 'AI算力卡', 'green', 3200, { desc: '老一代训练卡，显存带宽仍具价值。' }],
  ['c-token-deepseek-v3', 'DeepSeek V3 1000万 Token 包', '模型Token', 'green', 260, { desc: '高性价比国产推理额度，价格战影响显著。' }],
  ['c-token-qwen', 'Qwen3 1000万 Token 包', '模型Token', 'green', 240, { desc: '国产主流模型额度，随版本迭代贬值。' }],
  ['c-token-glm', 'GLM-4.6 1000万 Token 包', '模型Token', 'green', 230, { desc: '通用能力均衡，价格随促销频繁调整。' }],
  ['c-token-kimi', 'Kimi K2 1000万 Token 包', '模型Token', 'green', 280, { desc: '长文本推理额度，需求稳定。' }],
  ['c-token-mini', 'GPT-5 mini 1000万 Token 包', '模型Token', 'green', 320, { desc: '轻量版推理额度，代际更新后快速贬值。' }],
  ['c-dataset-speech', '语音克隆语料 100 小时', '数据集', 'green', 1800, { desc: '版权干净的语音数据，可用性高但供给充足。' }],
  ['c-dataset-code', '代码语料集 500GB', '数据集', 'green', 2600, { desc: '去重后的代码数据，价值随模型需求波动。' }],
  ['c-dataset-legal', '法律判决文书集 200万篇', '数据集', 'green', 3200, { desc: '公开文书整理集，法律 AI 的常见原料。' }],
  ['c-rent-4090-cluster', 'RTX 4090 八卡日租', '算力租赁', 'green', 620, { desc: '中小团队常用的日租集群，价格随供需波动。' }],
  ['c-rent-a100-week', 'A100 集群 单卡周租', '算力租赁', 'green', 1900, { desc: '训练推理常见租期，供给受数据中心影响。' }],
  ['c-lora-domain', '行业 LoRA 微调包（金融）', '算法模型', 'green', 2600, { desc: '行业微调权重，效果依赖数据质量。' }],
  ['c-quant-strategy', '量化交易策略模型（基础版）', '算法模型', 'green', 3800, { desc: '公开因子策略权重，收益不稳定导致折价。' }],
  ['c-rtx-3060-12g-cluster', 'RTX 3060 12G 推理节点', 'GPU', 'green', 1250, { desc: '大显存低功耗推理卡，二手供给充足。' }],
  ['c-rtx-2070', 'NVIDIA RTX 2070 8GB', 'GPU', 'green', 980, { desc: '上一代消费卡，价格随新卡发布持续下行。' }],
  ['c-rtx-2080ti', 'NVIDIA RTX 2080 Ti 11GB', 'GPU', 'green', 1850, { desc: '魔改显存版本在二手市场偶有溢价。' }],
  ['c-mi50', 'AMD Instinct MI50 32GB', 'AI算力卡', 'green', 2200, { desc: '大显存老卡，性价比吸引自建推理用户。' }],
  ['c-ascend-310', '华为昇腾 310 推理卡', 'AI算力卡', 'green', 2600, { desc: '国产推理卡，受供货与生态影响价格波动。' }],
  ['c-token-claude-haiku', 'Claude Haiku 1000万 Token 包', '模型Token', 'blue', 480, { desc: '轻量推理额度，随版本迭代贬值明显。' }],
  ['c-token-gpt5-full', 'GPT-5 100万 Token 包', '模型Token', 'blue', 1200, { desc: '旗舰模型的推理额度，价格随官方定价调整。' }],
  ['c-token-claude-opus', 'Claude Opus 50万 Token 包', '模型Token', 'blue', 1800, { desc: '顶级模型额度，单价高但需求刚性。' }],
  ['c-token-gemini', 'Gemini 2.5 Pro 1000万 Token 包', '模型Token', 'blue', 760, { desc: '多模态推理额度，随谷歌定价策略波动。' }],
  ['c-token-r1', 'DeepSeek R1 深度推理包 500万 Token', '模型Token', 'blue', 640, { desc: '长链推理额度，成本较高，价格有支撑。' }],
  ['c-dataset-face', '人脸识别数据集 100万条', '数据集', 'blue', 9600, { desc: '合规要求高，可流通版本稀缺度中等。' }],
  ['c-dataset-lidar', '自动驾驶激光雷达数据集 10万帧', '数据集', 'blue', 14500, { desc: '采集成本极高，供给受车队规模限制。' }],
  ['c-dataset-medical', '医疗影像标注集 5万例', '数据集', 'blue', 16800, { desc: '标注成本高且合规门槛严，价格坚挺。' }],
  ['c-dataset-finance', '金融舆情数据集 3年全量', '数据集', 'blue', 7200, { desc: '时效性强，过期后价值快速衰减。' }],
  ['c-dataset-multimodal', '多模态图文对 1亿组', '数据集', 'blue', 12500, { desc: '训练多模态模型的常用原料，供给受爬取政策影响。' }],
  ['c-rtx-4060ti-16g', 'NVIDIA RTX 4060 Ti 16GB', 'GPU', 'blue', 2900, { desc: '大显存入门卡，AI 用户与游戏用户共同定价。' }],
  ['c-rtx-4070ti-super', 'NVIDIA RTX 4070 Ti SUPER 16GB', 'GPU', 'blue', 5600, { desc: '中高端消费卡，价格受新卡发布压制。' }],
  ['c-rtx-3090-24g', 'NVIDIA RTX 3090 24GB', 'GPU', 'blue', 5400, { desc: '上代旗舰，二手价格随 4090 供给波动。' }],
  ['c-rtx-a4000', 'NVIDIA RTX A4000 16GB', 'GPU', 'blue', 6200, { desc: '专业卡，功耗低，工作站市场稳定需求。' }],
  ['c-rtx-a5000', 'NVIDIA RTX A5000 24GB', 'GPU', 'blue', 11800, { desc: '专业卡，受企业采购节奏影响。' }],
  ['c-mi210', 'AMD Instinct MI210 64GB', 'AI算力卡', 'blue', 42000, { desc: '数据中心推理卡，价格随大厂换代调整。' }],
  ['c-ascend-910b-lite', '华为昇腾 910B 推理版', 'AI算力卡', 'blue', 88000, { desc: '国产算力主力，受出口管制与产能双重影响。' }],
  ['c-mtt-s3000', '摩尔线程 MTT S3000', 'AI算力卡', 'blue', 4600, { desc: '国产图形与推理卡，生态成熟度影响定价。' }],
  ['c-rent-h100-hour', 'H100 集群 单卡时租', '算力租赁', 'blue', 55, { desc: '高端算力按小时计费，价格随供需紧张度变化。' }],
  ['c-rent-h100-month', 'H100 八卡月租', '算力租赁', 'blue', 260000, { desc: '团队级长期租约，价格谈判空间大。' }],
  ['c-rent-mi300-week', 'MI300X 单卡周租', '算力租赁', 'blue', 9800, { desc: '大显存推理租赁，性价比吸引中小团队。' }],
  ['c-lora-multimodal', '多模态 LoRA 风格包（全套）', '算法模型', 'blue', 8600, { desc: '成套风格权重，价格随创作者供给波动。' }],
  ['c-rag-index', '私有 RAG 索引 千万级向量', '算法模型', 'blue', 6800, { desc: '企业知识库索引，价值取决于数据独占性。' }],
  ['c-digital-human', '数字人驱动模型（含口型）', '算法模型', 'blue', 12500, { desc: '直播与短视频行业刚需，价格随需求波动。' }],
  ['c-whisper-ft', 'Whisper 微调模型（中文）', '算法模型', 'blue', 3600, { desc: '语音识别微调权重，随基座更新贬值。' }],
  ['c-rtx-5070', 'NVIDIA RTX 5070 12GB', 'GPU', 'purple', 4600, { desc: '新一代主流卡，价格受显存成本传导影响。' }],
  ['c-rtx-5070ti', 'NVIDIA RTX 5070 Ti 16GB', 'GPU', 'purple', 6600, { desc: '主流甜品卡，渠道价格波动频繁。' }],
  ['c-rtx-5080', 'NVIDIA RTX 5080 16GB', 'GPU', 'purple', 10500, { desc: '次旗舰消费卡，价格随 5090 供给紧张而抬升。' }],
  ['c-rtx-4080-super', 'NVIDIA RTX 4080 SUPER 16GB', 'GPU', 'purple', 8200, { desc: '上代次旗舰，停产前后价格易被拉起。' }],
  ['c-rtx-4090d', 'NVIDIA RTX 4090D 24GB', 'GPU', 'purple', 17499, { desc: '特供版本，合规因素带来额外溢价。' }],
  ['c-rtx-l4', 'NVIDIA L4 24GB', 'AI算力卡', 'purple', 16500, { desc: '低功耗推理卡，视频与推理混合负载常用。' }],
  ['c-rtx-l40s', 'NVIDIA L40S 48GB', 'AI算力卡', 'purple', 62000, { desc: '图形与推理兼顾，企业采购价格平稳。' }],
  ['c-mi325x', 'AMD Instinct MI325X 256GB', 'AI算力卡', 'purple', 260000, { desc: '超大显存推理卡，挑战既有市场格局。' }],
  ['c-ascend-910b', '华为昇腾 910B 64GB', 'AI算力卡', 'purple', 145000, { desc: '国产训练主力，受管制与产能双重驱动。' }],
  ['c-ascend-910c', '华为昇腾 910C', 'AI算力卡', 'purple', 285000, { desc: '国产新一代算力，供给紧张时价格暴涨。' }],
  ['c-gaudi-3', 'Intel Gaudi 3 加速卡', 'AI算力卡', 'purple', 108000, { desc: '性价比路线，价格随大厂采购策略波动。' }],
  ['c-cambricon-370', '寒武纪 MLU370-X8', 'AI算力卡', 'purple', 68000, { desc: '国产推理卡，生态适配度影响折价。' }],
  ['c-dataset-imagenet', 'ImageNet 完整版（含标注）', '数据集', 'purple', 68000, { desc: '计算机视觉的经典基准数据，商业授权价格高昂。' }],
  ['c-dataset-laion', 'LAION-5B 图文数据集快照', '数据集', 'purple', 46000, { desc: '超大规模图文对，合规整改后价值重估。' }],
  ['c-dataset-commoncrawl', 'Common Crawl 全量快照（清洗版）', '数据集', 'purple', 38000, { desc: '大模型预训练基础原料，清洗成本决定价值。' }],
  ['c-dataset-driving', '自动驾驶全场景数据集（百万帧）', '数据集', 'purple', 92000, { desc: '采集与标注成本极高，供给受车队限制。' }],
  ['c-model-sdxl-ft', 'Stable Diffusion XL 微调模型', '算法模型', 'purple', 26000, { desc: '成熟文生图微调权重，商用授权影响价格。' }],
  ['c-model-flux-ft', 'Flux.1 高质量微调模型', '算法模型', 'purple', 34000, { desc: '新一代文生图权重，受换代速度压制。' }],
  ['c-model-legal', '法律大模型 微调权重', '算法模型', 'purple', 42000, { desc: '专业领域模型，客户集中导致价格波动大。' }],
  ['c-rtx-5090', 'NVIDIA RTX 5090 32GB', 'GPU', 'gold', 32000, { desc: '消费卡旗舰，显存产能转移时常被炒高。' }],
  ['c-rtx-4090', 'NVIDIA RTX 4090 24GB', 'GPU', 'gold', 19500, { desc: '上代旗舰，是二手市场最硬的通货之一。' }],
  ['c-rtx-pro-6000', 'NVIDIA RTX PRO 6000 96GB', 'GPU', 'gold', 128000, { desc: '96GB 显存的工作站旗舰，本地大模型刚需。' }],
  ['c-a100-40g', 'NVIDIA A100 40GB PCIe', 'AI算力卡', 'gold', 420000, { desc: '训练主力卡，价格随数据中心换代波动。' }],
  ['c-a100-80g', 'NVIDIA A100 80GB SXM', 'AI算力卡', 'gold', 760000, { desc: '大显存训练卡，出口管制下供给紧张。' }],
  ['c-a800-80g', 'NVIDIA A800 80GB', 'AI算力卡', 'gold', 880000, { desc: '合规改款，管制放松时价格快速回落。' }],
  ['c-h800-80g', 'NVIDIA H800 80GB', 'AI算力卡', 'gold', 1250000, { desc: '特供型号，政策变化带来剧烈价格波动。' }],
  ['c-dataset-all', '全网中文多模态语料库（授权版）', '数据集', 'gold', 165000, { desc: '合规授权的超大规模语料，稀缺度极高。' }],
  ['c-model-llama4', 'Meta Llama 4 70B 权重文件', '算法模型', 'gold', 215000, { desc: '开源权重但商用授权与微调包稀缺。' }],
  ['c-model-deepseek-weights', 'DeepSeek V3 全量权重（商用授权）', '算法模型', 'gold', 268000, { desc: '商用授权权重，企业私有化部署刚需。' }],
  ['c-rent-h200-month', 'H200 八卡月租（独占）', '算力租赁', 'gold', 620000, { desc: '顶级算力独占租约，供给极紧。' }],
  ['c-h100-80g', 'NVIDIA H100 80GB SXM', 'AI算力卡', 'red', 520000, { desc: 'AI 训练标杆卡，供需缺口决定其金融属性。' }],
  ['c-h100-nvl', 'NVIDIA H100 NVL 94GB', 'AI算力卡', 'red', 680000, { desc: '大显存版本，推理场景溢价明显。' }],
  ['c-h200-141g', 'NVIDIA H200 141GB', 'AI算力卡', 'red', 3800000, { desc: '显存带宽旗舰，单卡价格足以买下一套房。' }],
  ['c-b200-180g', 'NVIDIA B200 180GB', 'AI算力卡', 'red', 4200000, { desc: '新一代旗舰算力，供给极度紧张的金融化标的。' }],
  ['c-gb200-nvl72', 'NVIDIA GB200 NVL72 整机柜', 'AI算力卡', 'red', 24000000, { desc: '整机柜超级算力，只有超大规模玩家参与定价。' }],
  ['c-mi300x', 'AMD Instinct MI300X 192GB', 'AI算力卡', 'red', 1650000, { desc: '超大显存推理卡，是高端算力市场的重要变量。' }],
);

/* =========================== 电脑配件 (120) =========================== */
W(HARDWARE,
  ['hw-e5-2680v4', 'Intel 至强 E5-2680 v4', 'CPU', 'white', 45, { desc: '洋垃圾平台主力，整机成本极低。' }],
  ['hw-e5-2666v3', 'Intel 至强 E5-2666 v3', 'CPU', 'white', 38, { desc: '老服务器拆机件，价格随拆机量波动。' }],
  ['hw-e3-1231v3', 'Intel 至强 E3-1231 v3', 'CPU', 'white', 95, { desc: '曾经的性价比神 U，现已跌入白菜价。' }],
  ['hw-g4560', 'Intel 奔腾 G4560', 'CPU', 'white', 78, { desc: '入门双核，办公机拆机件。' }],
  ['hw-g1840', 'Intel 赛扬 G1840', 'CPU', 'white', 28, { desc: '极低端双核，基本只作为亮机件。' }],
  ['hw-ddr4-8g-2666', 'DDR4 8G 2666 台式机内存', '内存', 'white', 85, { desc: '入门容量，价格随原厂颗粒报价波动。' }],
  ['hw-ddr4-8g-nb', 'DDR4 8G 3200 笔记本内存', '内存', 'white', 92, { desc: '笔记本升级件，需求稳定但供给充足。' }],
  ['hw-ssd-240g-sata', '240G SATA 固态硬盘', '固态', 'white', 88, { desc: '老平台升级件，被 NVMe 挤压价格空间。' }],
  ['hw-hdd-4t-bluedisk', '西数 4TB 蓝盘 机械硬盘', '固态', 'white', 520, { desc: '大容量冷存储，价格随存储颗粒周期波动。' }],
  ['hw-psu-400w', '航嘉 冷静王 400W 电源', '电源', 'white', 145, { desc: '入门电源，价格长期稳定。' }],
  ['hw-case-sama', '先马 黑洞 中塔机箱', '机箱', 'white', 168, { desc: '静音入门机箱，结构简单。' }],
  ['hw-cooler-ysj', '雅浚 G3 风冷散热器', '散热', 'white', 96, { desc: '百元级风冷，销量极大。' }],
  ['hw-kb-shuangfeiyan', '双飞燕 有线键盘', '外设', 'white', 45, { desc: '办公耗材，价格几乎不变。' }],
  ['hw-psu-changcheng', '长城 500W 电源', '电源', 'white', 215, { desc: '主流入门电源，随铜价小幅波动。' }],
  ['hw-case-lianli-o11', '联力 O11 Dynamic 海景房机箱', '机箱', 'white', 620, { desc: '网红机箱，价格随渠道促销波动。' }],
  ['hw-ram-16g-ddr4-no', '杂牌 DDR4 16G 3200 内存', '内存', 'white', 320, { desc: '白牌颗粒，稳定性差导致折价。' }],
  ['hw-mining-rig', '显卡矿机 8 卡平台（无卡）', '矿卡', 'white', 280, { desc: '矿潮遗物，只剩铁架子还有价值。' }],
  ['hw-used-office-pc', '二手办公整机 (i5-4570/8G)', '整机', 'white', 480, { desc: '企业淘汰机，量大价低。' }],
  ['hw-netbar-pc', '网吧退役整机 (i5-9400F/16G)', '整机', 'green', 1250, { desc: '成色参差，价格随网吧换代集中释放。' }],
  ['hw-rtx750ti', 'NVIDIA GTX 750 Ti 2GB', '显卡', 'green', 175, { desc: '退役亮机卡，价格见底后略有回升。' }],
  ['hw-gtx960', 'NVIDIA GTX 960 2GB', '显卡', 'green', 240, { desc: '老卡，仅剩亮机与怀旧需求。' }],
  ['hw-gtx1060-6g', 'NVIDIA GTX 1060 6GB', '显卡', 'green', 520, { desc: '史上最普及的游戏卡，二手供给巨大。' }],
  ['hw-gtx1660s', 'NVIDIA GTX 1660 SUPER 6GB', '显卡', 'green', 780, { desc: '1080p 主流老卡，价格随新卡发布走低。' }],
  ['hw-rx580', 'AMD RX 580 2048SP 8GB', '矿卡', 'green', 310, { desc: '矿卡代表型号，价格与矿潮记忆绑定。' }],
  ['hw-rtx2060', 'NVIDIA RTX 2060 6GB', '显卡', 'green', 890, { desc: '光追入门卡，二手价格稳定。' }],
  ['hw-i3-12100f', 'Intel i3-12100F', 'CPU', 'green', 450, { desc: '入门游戏神 U，价格随平台换代下调。' }],
  ['hw-i3-10105f', 'Intel i3-10105F', 'CPU', 'green', 330, { desc: '过气入门 U，装机预算优先项。' }],
  ['hw-r5-5500', 'AMD Ryzen 5 5500', 'CPU', 'green', 560, { desc: '低价六核，散片价格随需求波动。' }],
  ['hw-r5-5600', 'AMD Ryzen 5 5600', 'CPU', 'green', 620, { desc: 'AM4 平台主力，缺货时价格上浮明显。' }],
  ['hw-r5-3600', 'AMD Ryzen 5 3600', 'CPU', 'green', 430, { desc: 'Zen2 主力，随换代跌价。' }],
  ['hw-r5-1600af', 'AMD Ryzen 5 1600 AF', 'CPU', 'green', 320, { desc: '曾经的性价比之王，现存皆二手。' }],
  ['hw-x570', 'X570 主板（华硕 TUF）', '主板', 'green', 560, { desc: 'AM4 高端芯片组，二手价格随平台退出下行。' }],
  ['hw-b550', 'B550 主板（微星迫击炮）', '主板', 'green', 520, { desc: 'AM4 主流选择，供给稳定。' }],
  ['hw-h610', 'H610 主板', '主板', 'green', 420, { desc: '入门 LGA1700 主板，价格随 CPU 促销联动。' }],
  ['hw-ddr4-16g-3200', 'DDR4 16G 3200 内存条', '内存', 'green', 450, { desc: '主流容量，价格随原厂颗粒报价剧烈波动。' }],
  ['hw-ddr4-32g-3600', 'DDR4 32G 3600 灯条', '内存', 'green', 780, { desc: '大容量高频灯条，需求受新平台挤压。' }],
  ['hw-ddr5-16g-5600', 'DDR5 16G 5600 内存条', '内存', 'green', 420, { desc: 'DDR5 入门容量，价格随颗粒代际下行。' }],
  ['hw-ddr4-nb-16g', 'DDR4 16G 3200 笔记本内存', '内存', 'green', 260, { desc: '笔记本升级件，老机型需求稳定。' }],
  ['hw-ssd-1t-nvme', '1TB NVMe SSD (PCIe3.0)', '固态', 'green', 420, { desc: '主流容量固态，价格与存储周期高度相关。' }],
  ['hw-ssd-500g-nvme', '500GB NVMe SSD', '固态', 'green', 260, { desc: '入门容量，价格竞争激烈。' }],
  ['hw-hdd-16t-enterprise', '16TB 企业级氦气硬盘', '固态', 'green', 1780, { desc: '大容量冷存储，受数据中心需求影响。' }],
  ['hw-psu-leadex-650', '振华 LEADEX G 650W 金牌', '电源', 'green', 420, { desc: '主流金牌电源，价格随铜与电容成本波动。' }],
  ['hw-psu-cm-gx750', '酷冷至尊 GX750 金牌', '电源', 'green', 460, { desc: '中端电源，渠道价格稳定。' }],
  ['hw-cooler-nhd15', 'Noctua NH-D15 风冷散热器', '散热', 'green', 700, { desc: '风冷天花板，价格极少打折。' }],
  ['hw-cooler-fc140', '利民 FC140 双塔风冷', '散热', 'green', 240, { desc: '性价比之王，销量压制进口品牌。' }],
  ['hw-cooler-360aio', '360 一体式水冷（通用款）', '散热', 'green', 520, { desc: '水冷入门款，价格随泵体方案迭代。' }],
  ['hw-mon-24-144', '24寸 1080p 144Hz 显示器', '显示器', 'green', 620, { desc: '电竞入门屏，面板价格决定成本。' }],
  ['hw-mouse-g502', '罗技 G502 鼠标', '外设', 'green', 260, { desc: '经典游戏鼠标，促销期价格下探。' }],
  ['hw-mining-3090-rig', '矿机整机 (8×RTX 3060)', '矿卡', 'green', 8600, { desc: '矿潮整机残值，拆卡出售是主要出路。' }],
  ['hw-i5-12400f', 'Intel i5-12400F', 'CPU', 'blue', 760, { desc: '主流六核，价格随换代与促销波动。' }],
  ['hw-i5-13400f', 'Intel i5-13400F', 'CPU', 'blue', 1080, { desc: '主流十核，盒装散片价差明显。' }],
  ['hw-i5-14600kf', 'Intel i5-14600KF', 'CPU', 'blue', 1450, { desc: '高主频游戏 U，价格受新一代压制。' }],
  ['hw-i7-12700kf', 'Intel i7-12700KF', 'CPU', 'blue', 1380, { desc: '上代高端，二手与散片供给充足。' }],
  ['hw-r7-5700x3d', 'AMD Ryzen 7 5700X3D', 'CPU', 'blue', 1080, { desc: 'AM4 平台最后的大缓存升级项，停产易涨价。' }],
  ['hw-r7-7600x', 'AMD Ryzen 5 7600X', 'CPU', 'blue', 1180, { desc: 'AM5 入门，价格随主板促销联动。' }],
  ['hw-r7-9600x', 'AMD Ryzen 5 9600X', 'CPU', 'blue', 1450, { desc: '新一代中端，能效比优秀。' }],
  ['hw-rtx3050', 'NVIDIA RTX 3050 8GB', '显卡', 'blue', 1350, { desc: '入门光追卡，性价比争议大。' }],
  ['hw-rtx3060-12g', 'NVIDIA RTX 3060 12GB', '显卡', 'blue', 1420, { desc: '大显存主流卡，二手与新品价格互相牵制。' }],
  ['hw-rtx4060', 'NVIDIA RTX 4060 8GB', '显卡', 'blue', 2180, { desc: '主流甜品卡，价格随新卡发布下调。' }],
  ['hw-rtx4060ti', 'NVIDIA RTX 4060 Ti 8GB', '显卡', 'blue', 2680, { desc: '中端卡，显存容量常被诟病。' }],
  ['hw-rtx4070', 'NVIDIA RTX 4070 12GB', '显卡', 'blue', 3950, { desc: '2K 主流卡，停产前后价格易反弹。' }],
  ['hw-rx6600', 'AMD RX 6600 8GB', '显卡', 'blue', 1180, { desc: '性价比甜点，矿卡冲击后价格回落。' }],
  ['hw-rx6700xt', 'AMD RX 6700 XT 12GB', '显卡', 'blue', 1380, { desc: '2K 入门，二手供给主要来自矿场。' }],
  ['hw-rx6800xt', 'AMD RX 6800 XT 16GB', '显卡', 'blue', 2100, { desc: '大显存老旗舰，价格随 3A 需求波动。' }],
  ['hw-arc-a750', 'Intel Arc A750 8GB', '显卡', 'blue', 1250, { desc: '驱动优化提升后需求回升，价格弹性大。' }],
  ['hw-arc-b580', 'Intel Arc B580 12GB', '显卡', 'blue', 1850, { desc: '新一代性价比选手，供货紧张时溢价。' }],
  ['hw-z690', 'Z690 主板（华硕吹雪）', '主板', 'blue', 1180, { desc: 'LGA1700 高端芯片组，价格随平台退出下行。' }],
  ['hw-b660', 'B660 主板（微星迫击炮）', '主板', 'blue', 720, { desc: '主流 LGA1700 主板，促销频繁。' }],
  ['hw-b760', 'B760 主板', '主板', 'blue', 860, { desc: '新一代主流芯片组，价格稳定。' }],
  ['hw-a620', 'A620 主板', '主板', 'blue', 620, { desc: 'AM5 入门芯片组，降低新平台门槛。' }],
  ['hw-ddr5-32g-6000', 'DDR5 32G 6000 内存套条', '内存', 'blue', 1180, { desc: 'AM5 甜点频率，价格随颗粒产能波动剧烈。' }],
  ['hw-ddr5-48g-7200', 'DDR5 48G 7200 高频套条', '内存', 'blue', 1980, { desc: '高频大容量，需求集中在小众玩家。' }],
  ['hw-ddr5-nb-16g', 'DDR5 16G 5600 笔记本内存', '内存', 'blue', 380, { desc: '新平台笔记本升级件，价格下行趋势明显。' }],
  ['hw-gskill-royal', '芝奇 皇家戟 DDR5 32G 6400', '内存', 'blue', 1680, { desc: '灯条旗舰，品牌溢价明显。' }],
  ['hw-ssd-2t-pcie4', '2TB NVMe SSD PCIe4.0', '固态', 'blue', 960, { desc: '主流大容量固态，价格与存储周期直接挂钩。' }],
  ['hw-ssd-4t-pcie4', '4TB NVMe SSD PCIe4.0', '固态', 'blue', 1780, { desc: '内容创作者常用容量，缺货时涨价。' }],
  ['hw-ssd-1t-pcie5', '1TB NVMe SSD PCIe5.0', '固态', 'blue', 1180, { desc: '新一代接口，主控发热问题影响口碑。' }],
  ['hw-ssd-990pro', '三星 990 PRO 2TB', '固态', 'blue', 1580, { desc: '一线品牌旗舰固态，价格随原厂策略波动。' }],
  ['hw-ssd-sn850x', '西数 SN850X 2TB', '固态', 'blue', 1420, { desc: '主流旗舰固态，促销期价格下探明显。' }],
  ['hw-ssd-tiplus7100', '致态 TiPlus7100 2TB', '固态', 'blue', 1080, { desc: '国产颗粒代表，价格优势明显。' }],
  ['hw-ssd-980pro', '三星 980 PRO 1TB', '固态', 'blue', 720, { desc: '上代旗舰，随新一代发布降价。' }],
  ['hw-ssd-u2-384', '企业级 U.2 SSD 3.84TB', '固态', 'blue', 4600, { desc: '服务器拆机盘，写入寿命决定残值。' }],
  ['hw-psu-rm850x', '海盗船 RM850x 金牌全模组', '电源', 'blue', 880, { desc: '经典高端电源，价格长期稳定。' }],
  ['hw-psu-rog1200', '华硕 ROG 1200W 白金电源', '电源', 'blue', 2280, { desc: '旗舰电源，受高端卡供电需求拉动。' }],
  ['hw-psu-seasonic-1000', '海韵 FOCUS GX-1000', '电源', 'blue', 1080, { desc: '口碑稳定，价格随元器件成本波动。' }],
  ['hw-cooler-h150i', '海盗船 H150i 360 水冷', '散热', 'blue', 1180, { desc: '品牌水冷，价格随新品迭代下探。' }],
  ['hw-mon-27-2k', '27寸 2K 165Hz 显示器', '显示器', 'blue', 1280, { desc: '主流电竞屏，面板价格波动传导明显。' }],
  ['hw-mon-32-4k', '32寸 4K 144Hz 显示器', '显示器', 'blue', 2680, { desc: '高分高刷，受面板产能与汇率影响。' }],
  ['hw-mouse-gpw', '罗技 G PRO X Superlight', '外设', 'blue', 780, { desc: '电竞鼠标标杆，价格随赛事热度波动。' }],
  ['hw-kb-razer', '雷蛇 猎魂光蛛 V3', '外设', 'blue', 980, { desc: '光轴键盘，品牌溢价稳定。' }],
  ['hw-r7-7800x3d', 'AMD Ryzen 7 7800X3D', 'CPU', 'gold', 1900, { desc: '游戏性能标杆，停产消息常引发涨价。' }],
  ['hw-r7-5800x3d', 'AMD Ryzen 7 5800X3D', 'CPU', 'gold', 2450, { desc: 'AM4 封神缓存 U，缺货时价格高于首发。' }],
  ['hw-r7-9800x3d', 'AMD Ryzen 7 9800X3D', 'CPU', 'gold', 3200, { desc: '新一代游戏之王，供货紧张期溢价严重。' }],
  ['hw-r9-9950x3d', 'AMD Ryzen 9 9950X3D', 'CPU', 'gold', 5200, { desc: '双 CCD 旗舰，兼顾游戏与生产力。' }],
  ['hw-i9-14900k', 'Intel i9-14900K', 'CPU', 'gold', 3600, { desc: '上代旗舰，稳定性争议影响二手价格。' }],
  ['hw-i9-13900k', 'Intel i9-13900K', 'CPU', 'gold', 2980, { desc: '高频多核，散热要求推高平台成本。' }],
  ['hw-i7-14700k', 'Intel i7-14700K', 'CPU', 'gold', 2450, { desc: '性价比旗舰，价格随新一代发布下调。' }],
  ['hw-epyc-9654', 'AMD EPYC 9654 服务器 CPU', 'CPU', 'gold', 48000, { desc: '96 核服务器处理器，企业采购驱动价格。' }],
  ['hw-rtx3080-10g', 'NVIDIA RTX 3080 10GB', '显卡', 'gold', 2750, { desc: '上代旗舰，矿潮退去后价格长期承压。' }],
  ['hw-rtx4070super', 'NVIDIA RTX 4070 SUPER 12GB', '显卡', 'gold', 4680, { desc: '2K 高刷主力，停产前后易被拉涨。' }],
  ['hw-rtx4080', 'NVIDIA RTX 4080 16GB', '显卡', 'gold', 6800, { desc: '上一代次旗舰，供给减少后价格坚挺。' }],
  ['hw-rx7900xtx', 'AMD RX 7900 XTX 24GB', '显卡', 'gold', 6200, { desc: 'A 卡旗舰，价格战影响明显。' }],
  ['hw-rtx3090-24g', 'NVIDIA RTX 3090 24GB 涡轮版', '显卡', 'gold', 5400, { desc: '大显存上代旗舰，AI 用户抬高了残值。' }],
  ['hw-z790', 'Z790 主板（华硕 ROG）', '主板', 'gold', 2680, { desc: '高端 LGA1700 主板，价格随平台换代下跌。' }],
  ['hw-x670e', 'X670E 主板（技嘉大师）', '主板', 'gold', 2980, { desc: 'AM5 旗舰芯片组，PCIe5 通道数是卖点。' }],
  ['hw-z890', 'Z890 主板', '主板', 'gold', 3280, { desc: '新一代旗舰芯片组，首发溢价明显。' }],
  ['hw-ddr5-64g-6400', 'DDR5 64G 6400 套条', '内存', 'gold', 3680, { desc: '大容量高频，受颗粒产能转移影响最大。' }],
  ['hw-ddr5-ecc-64g', 'DDR5 ECC RDIMM 64G', '内存', 'gold', 8600, { desc: '服务器容错内存，数据中心需求驱动价格。' }],
  ['hw-ddr4-ecc-32g', 'DDR4 ECC RDIMM 32G', '内存', 'gold', 1280, { desc: '洋垃圾平台适配内存，价格随拆机量波动。' }],
  ['hw-ssd-ent-768t', '企业级 NVMe SSD 7.68TB', '固态', 'gold', 16800, { desc: '数据中心级容量，企业采购价波动剧烈。' }],
  ['hw-hdd-24t-ent', '24TB 企业级硬盘', '固态', 'gold', 4200, { desc: '最大容量级别机械盘，受数据中心订单影响。' }],
  ['hw-cooler-custom-loop', '分体水冷 全套（CPU+GPU）', '散热', 'gold', 5800, { desc: '定制方案，价格取决于冷头与泵体品牌。' }],
  ['hw-cooler-industrial-fan', '工业级暴力风扇（3000rpm）', '散热', 'gold', 260, { desc: '服务器级风压件，噪音极大但性能强。' }],
  ['hw-rtx5080', 'NVIDIA RTX 5080 16GB 三风扇', '显卡', 'gold', 10800, { desc: '新一代次旗舰，显存成本直接决定价格。' }],
  ['hw-rtx5070ti', 'NVIDIA RTX 5070 Ti 16GB 超频版', '显卡', 'gold', 6800, { desc: '主流甜点，渠道价格波动频繁。' }],
  ['hw-rtx5060', 'NVIDIA RTX 5060 8GB', '显卡', 'gold', 2480, { desc: '新一代入门卡，定价争议带来需求波动。' }],
  ['hw-mon-oled-240', '27寸 OLED 240Hz 显示器', '显示器', 'gold', 5800, { desc: 'OLED 电竞屏，面板良率影响价格。' }],
  ['hw-rtx4090', 'NVIDIA RTX 4090 24GB 公版', '显卡', 'red', 19800, { desc: '上代卡皇，是二手市场最硬的通货之一。' }],
  ['hw-rtx5090', 'NVIDIA RTX 5090 32GB 公版', '显卡', 'red', 32800, { desc: '当代卡皇，显存产能转移时常被炒到天价。' }],
  ['hw-r9-9950x', 'AMD Ryzen 9 9950X', 'CPU', 'red', 4600, { desc: '生产力旗舰，价格随缺货周期剧烈波动。' }],
  ['hw-mac-studio-m3ultra', 'Apple Mac Studio M3 Ultra 512G', '整机', 'red', 62000, { desc: '统一内存架构的本地推理整机，供不应求。' }],
  ['hw-dgx-spark', 'NVIDIA DGX Spark 开发者整机', '整机', 'red', 32000, { desc: '桌面级 AI 整机，首发供给极紧。' }],
);

/* ================== 虚拟股票 / 房产 / 收藏 (100) ================== */
W(ASSETS,
  ['a-coin-yuan', '老版人民币 整刀（三版）', '钱币', 'white', 320, { desc: '存量巨大，品相决定价格，炒作周期极短。' }],
  ['a-coin-silver', '袁大头 银元（普通版）', '钱币', 'white', 780, { desc: '存世量大，真假混杂导致折价。' }],
  ['a-stamp-80', '80 分邮票 整版', '邮票', 'white', 180, { desc: '邮政发行量巨大，收藏需求低迷。' }],
  ['a-stamp-firstday', '首日封 一套', '邮票', 'white', 95, { desc: '集邮寒冬下价格长期横盘。' }],
  ['a-cassette-fc', 'FC 红白机 卡带（散装）', '复古游戏', 'white', 68, { desc: '老游戏卡带，成色与兼容性决定成交。' }],
  ['a-game-cd', '红色警戒 初版光盘', '复古游戏', 'white', 120, { desc: '光盘老化严重，仅存情怀价值。' }],
  ['a-parking-slot', '停车场 车位（虚拟产权）', '虚拟房产', 'white', 45000, { desc: '最基础的实体类虚拟资产，涨幅缓慢。' }],
  ['a-old-town-1br', '老城区 一室一厅 42㎡', '虚拟房产', 'white', 68000, { desc: '流动性最好的入门房产，租金回报稳定。' }],
  ['a-suburb-store', '郊区 临街小店 30㎡', '虚拟房产', 'white', 92000, { desc: '受商圈迁移影响大的小体量商铺。' }],
  ['a-warehouse', '城郊 仓库厂房 300㎡', '虚拟房产', 'white', 156000, { desc: '工业用地属性，价格跟随物流景气度。' }],
  ['a-campground', '露营地 地块（含许可）', '数字土地', 'white', 88000, { desc: '文旅概念土地，季节性价格波动明显。' }],
  ['a-guild-base', '游戏公会 基地（大型）', '虚拟房产', 'white', 36000, { desc: '依赖游戏活跃度，退游潮即贬值。' }],
  ['a-racetrack', '虚拟赛车场 赛道 使用权', '虚拟房产', 'white', 128000, { desc: '小众场景资产，成交周期长。' }],
  ['a-usdt', 'USDT 稳定币持仓', '虚拟持仓', 'white', 7.2, { vol: 0.005, desc: '锚定美元的稳定币，波动极小，作为现金等价物。' }],
  ['a-dogecoin', '狗狗币持仓 DOGE', '虚拟持仓', 'white', 2.1, { vol: 0.2, desc: '情绪驱动型资产，一条推文就能带来两位数波动。' }],
  ['a-coin-panda', '熊猫金币 30g', '钱币', 'green', 16800, { desc: '随金价波动，兼具收藏与贵金属属性。' }],
  ['a-coin-commemorate', '奥运纪念币 全套', '钱币', 'green', 2300, { desc: '发行量大，赛事过后价格回落。' }],
  ['a-stamp-zodiac', '生肖邮票 整版（早期）', '邮票', 'green', 1600, { desc: '行情好坏全看资金是否回流集邮板块。' }],
  ['a-stamp-error', '错版邮票 单枚', '邮票', 'green', 4200, { desc: '错版带来的稀缺性，鉴定门槛高。' }],
  ['a-manga-first', '初版漫画 单行本（全套）', '实物收藏', 'green', 3200, { desc: '纸品保存难度大，品相差异决定价格。' }],
  ['a-watch-vintage', '古董腕表（手动上链）', '实物收藏', 'green', 8600, { desc: '机械表收藏小众，流通依赖拍卖行。' }],
  ['a-pen-limited', '限量钢笔（编号款）', '实物收藏', 'green', 5400, { desc: '文具收藏细分市场，价格随品牌联名波动。' }],
  ['a-vinyl-first', '黑胶唱片 首版', '实物收藏', 'green', 2800, { desc: '首版压片溢价明显，品相影响巨大。' }],
  ['a-camera-film', '老式胶卷相机（可用）', '实物收藏', 'green', 1950, { desc: '胶片复兴带来需求，但供给逐年减少。' }],
  ['a-console-new', '老游戏机 全新未拆', '复古游戏', 'green', 6800, { desc: '未拆封状态是价格的核心，氧化风险高。' }],
  ['a-arcade-board', '街机主板（原装）', '复古游戏', 'green', 4600, { desc: '维修难度大，价格取决于稀有度与可用性。' }],
  ['a-short-id', '稀有游戏 ID（6 位数字）', '潮玩', 'green', 12000, { desc: '账号交易受限，价格随游戏热度剧烈波动。' }],
  ['a-mount-rare', '游戏内稀有坐骑（可交易）', '潮玩', 'green', 8800, { desc: '依赖版本强度，一次削弱就能腰斩。' }],
  ['a-tcg-pack', '集换卡 原封箱（24 盒）', '卡牌', 'green', 32000, { desc: '开箱即贬值，整箱惜售者多，价格坚挺。' }],
  ['a-sneaker-signature', '亲签球鞋 全球限量', '体育收藏', 'green', 46000, { desc: '签名真伪与赛事表现共同决定价格。' }],
  ['a-jersey-signed', '签名球衣（现役球星）', '体育收藏', 'green', 26000, { desc: '球员状态与转会消息直接冲击价格。' }],
  ['a-neighborhood-3br', '新城区 三室两厅 96㎡', '虚拟房产', 'green', 210000, { desc: '主流改善型房产，价格跟随城市指数。' }],
  ['a-metaverse-core', '元宇宙核心地块 128㎡', '数字土地', 'green', 320000, { desc: '虚拟世界的核心区土地，投机属性极强。' }],
  ['a-metaverse-shop', '元宇宙商业街 店面', '数字商铺', 'green', 420000, { desc: '租金收益取决于虚拟世界的活跃用户数。' }],
  ['a-metaverse-gallery', '元宇宙美术馆 展位', '数字商铺', 'green', 130000, { desc: '数字艺术带动的小众资产，价格波动大。' }],
  ['a-rental-yard', '民宿小院 经营权', '虚拟房产', 'green', 168000, { desc: '现金流型资产，淡旺季价格差异明显。' }],
  ['a-hotel-room', '电竞酒店 房间产权', '虚拟房产', 'green', 246000, { desc: '受电竞赛事与旅游周期双重影响。' }],
  ['a-arena', '虚拟演唱会 场地', '虚拟房产', 'green', 380000, { desc: '单次活动收益极高，但闲置期成本也高。' }],
  ['a-hangar', '停机坪 地块', '数字土地', 'green', 268000, { desc: '高端虚拟配套，需求极窄。' }],
  ['a-undersea-dc', '海底数据中心 地块', '数字土地', 'green', 620000, { desc: '算力概念地块，随 AI 资本开支预期波动。' }],
  ['a-golf-member', '虚拟高尔夫球场 会员位', '虚拟房产', 'green', 148000, { desc: '社交属性资产，价格黏性较强。' }],
  ['a-btc', '比特币虚拟持仓 BTC', '虚拟持仓', 'red', 780000, { vol: 0.15, desc: '波动极大的风险资产，单周两位数涨跌是常态。' }],
  ['a-eth', '以太坊虚拟持仓 ETH', '虚拟持仓', 'red', 26000, { vol: 0.12, desc: '与生态活跃度强相关，波动幅度高于主流股票。' }],
  ['a-nvda-stock', '英伟达虚拟股 NVDA', '虚拟股票', 'red', 1050, { vol: 0.08, desc: 'AI 算力叙事核心，财报前后波动剧烈。' }],
  ['a-card-charizard', '宝可梦 喷火龙 初版卡 PSA10', '卡牌', 'red', 1280000, { desc: '评级完美品相的天花板卡，价格由极少数藏家决定。' }],
  ['a-card-black-lotus', '万智牌 黑莲花（Power 9）', '卡牌', 'red', 3600000, { desc: '收藏卡领域的圣杯，全球存世不足千枚。' }],
  ['a-nft-001', '数字艺术品 #001', 'NFT艺术品', 'red', 520000, { vol: 0.2, desc: '编号第一的作品，价格完全由叙事和情绪驱动。' }],
  ['a-nft-ape', '无聊猿 系列头部编号', 'NFT艺术品', 'red', 860000, { vol: 0.18, desc: '蓝筹 NFT，随加密市场整体情绪同步剧烈波动。' }],
  ['a-villa-seaview', '海景别墅（虚拟产权）', '虚拟房产', 'red', 2400000, { desc: '虚拟世界最贵的居住类资产，只有少数买家参与。' }],
  ['a-private-island', '虚拟岛屿（私有）', '数字土地', 'red', 5600000, { desc: '稀缺的独立地块，流动性极差但报价坚挺。' }],
  ['a-maotai-stock', '贵州茅台虚拟股', '虚拟股票', 'gold', 1580, { vol: 0.03, desc: '消费核心资产，波动温和但长期趋势明确。' }],
  ['a-tsmc-stock', '台积电虚拟股 TSM', '虚拟股票', 'gold', 240, { vol: 0.05, desc: '先进制程代工龙头，受地缘与资本开支影响。' }],
  ['a-tencent-stock', '腾讯控股虚拟股', '虚拟股票', 'gold', 460, { vol: 0.05, desc: '游戏与社交基本盘，政策消息影响估值。' }],
  ['a-apple-stock', '苹果虚拟股 AAPL', '虚拟股票', 'gold', 185, { vol: 0.03, desc: '现金流稳定，价格围绕产品周期与回购节奏。' }],
  ['a-microsoft-stock', '微软虚拟股 MSFT', '虚拟股票', 'gold', 380, { vol: 0.03, desc: '云与 AI 双重叙事，估值对资本开支敏感。' }],
  ['a-tesla-stock', '特斯拉虚拟股 TSLA', '虚拟股票', 'gold', 268, { vol: 0.1, desc: '预期驱动型股票，交付数据与舆论放大波动。' }],
  ['a-meta-stock', 'Meta 虚拟股 META', '虚拟股票', 'gold', 620, { vol: 0.06, desc: '广告收入与元宇宙投入的拉扯决定估值。' }],
  ['a-amazon-stock', '亚马逊虚拟股 AMZN', '虚拟股票', 'gold', 198, { vol: 0.05, desc: '零售与云业务分化，财报季波动放大。' }],
  ['a-google-stock', '谷歌虚拟股 GOOGL', '虚拟股票', 'gold', 176, { vol: 0.04, desc: '搜索广告基本盘叠加模型竞争压力。' }],
  ['a-amd-stock', 'AMD 虚拟股', '虚拟股票', 'gold', 182, { vol: 0.08, desc: '与英伟达形成算力双雄格局，份额变化即价格变化。' }],
  ['a-alibaba-stock', '阿里巴巴虚拟股 BABA', '虚拟股票', 'gold', 138, { vol: 0.06, desc: '电商与云业务重估，受政策与竞争双压。' }],
  ['a-byd-stock', '比亚迪虚拟股', '虚拟股票', 'gold', 268, { vol: 0.07, desc: '新能源车龙头，销量与价格战消息直接驱动。' }],
  ['a-cambricon-stock', '寒武纪虚拟股', '虚拟股票', 'gold', 620, { vol: 0.12, desc: '国产算力概念股，情绪波动远大于基本面。' }],
  ['a-netease-stock', '网易虚拟股', '虚拟股票', 'gold', 168, { vol: 0.05, desc: '游戏流水稳定，新品周期带来估值波动。' }],
  ['a-pdd-stock', '拼多多虚拟股 PDD', '虚拟股票', 'gold', 148, { vol: 0.08, desc: '低价电商份额变化剧烈影响估值。' }],
  ['a-samsung-stock', '三星电子虚拟股', '虚拟股票', 'gold', 210, { vol: 0.05, desc: '存储周期决定利润，价格与内存现货联动。' }],
  ['a-sol-stock', 'Solana 虚拟持仓 SOL', '虚拟持仓', 'gold', 1450, { vol: 0.14, desc: '高性能公链代币，生态热度决定价格弹性。' }],
  ['a-card-ssr', 'SSR 限量卡牌（编号 001）', '卡牌', 'gold', 52000, { desc: '编号与卡面品相共同决定价格，炒作周期短。' }],
  ['a-card-rookie', '球星卡 新秀卡 PSA9', '卡牌', 'gold', 38000, { desc: '球员表现直接决定卡价，赛事期溢价明显。' }],
  ['a-car-holo', '初版 holographic 卡 PSA10', '卡牌', 'gold', 128000, { desc: '闪卡收藏的核心品种，评级后价格跳档。' }],
  ['a-card-yugioh', '游戏王 青眼白龙 初版', '卡牌', 'gold', 86000, { desc: '情怀与稀缺叠加，海外拍卖价格是定价参考。' }],
  ['a-sneaker-collab', '限量球鞋 联名款', '实物收藏', 'gold', 32000, { vol: 0.08, desc: '联名热度决定溢价，补货消息会导致暴跌。' }],
  ['a-figure-1of1', '限量手办 1/1', '手办', 'gold', 108000, { desc: '孤品属性带来极高溢价，成交极度依赖拍卖。' }],
  ['a-comic-manuscript', '亲签漫画手稿', '实物收藏', 'gold', 168000, { desc: '作者声誉与保存状况共同决定价值。' }],
  ['a-wristwatch-lux', '限量奢华腕表（带原盒）', '实物收藏', 'gold', 268000, { desc: '二级市场行情与世界拍卖同步，波动明显。' }],
  ['a-metaverse-land-core', '元宇宙核心商圈 整层', '数字商铺', 'gold', 980000, { desc: '虚拟世界的黄金商铺，租金与地价互相推升。' }],
  ['a-penthouse', '中心商务区 顶层公寓', '虚拟房产', 'gold', 620000, { desc: '虚拟城市的地标住宅，稀缺度极高的身份资产。' }],
  ['a-school-district', '学区房 90㎡（虚拟产权）', '虚拟房产', 'gold', 205000, { desc: '政策消息敏感型资产，利空时跌幅最猛。' }],
  ['a-store-commercial', '元宇宙商业街 旗舰店面', '数字商铺', 'gold', 315000, { desc: '品牌入驻带来租金预期，投机资金进出频繁。' }],
  ['a-stamp-rare', '稀有邮票 单枚（清票）', '邮票', 'blue', 26000, { desc: '存世稀少的早期票品，价格稳定但成交缓慢。' }],
  ['a-colored-coin', '稀有钱币 试铸样币', '钱币', 'blue', 46000, { desc: '样币存世极少，鉴定与流传有序才算高价。' }],
  ['a-figure-limited', '限量手办（限定版）', '手办', 'blue', 8600, { desc: '再版风险是主要利空，初版溢价明显。' }],
  ['a-blindbox-hidden', '绝版盲盒 隐藏款', '潮玩', 'blue', 12800, { desc: '隐藏款概率极低，价格随系列热度起落。' }],
  ['a-console-cart', '绝版游戏卡带（品相极佳）', '复古游戏', 'blue', 9800, { desc: '品相与完整配件是核心，价格逐年抬升。' }],
  ['a-postcard-set', '民国时期 明信片 全套', '实物收藏', 'blue', 16800, { desc: '史料价值与品相共同决定价格，圈子很小。' }],
  ['a-jersey-retro', '复古签名球衣（退役球星）', '体育收藏', 'blue', 32000, { desc: '球星历史地位带来长期稳定需求。' }],
  ['a-perfume-limited', '限量香水（停产款）', '实物收藏', 'blue', 5400, { desc: '停产消息是主要催化剂，保存期限是风险。' }],
  ['a-metaverse-stage', '元宇宙演艺舞台 长期位', '数字商铺', 'blue', 186000, { desc: '内容方需求驱动租金，热度退潮即贬值。' }],
  ['a-luxury-apt', '江景大平层 180㎡', '虚拟房产', 'blue', 388000, { desc: '高端虚拟住宅，价格跟随虚拟城市指数。' }],
  ['a-townhouse', '联排别墅（虚拟产权）', '虚拟房产', 'blue', 468000, { desc: '改善型资产，成交量集中在行情上行期。' }],
  ['a-standalone-villa', '独栋别墅（虚拟产权）', '虚拟房产', 'blue', 880000, { desc: '稀缺独立地块，价格抗跌性强。' }],
  ['a-office-half', '写字楼 半层（虚拟产权）', '虚拟房产', 'blue', 520000, { desc: '商业地产属性，租金回报决定估值中枢。' }],
  ['a-metaverse-plot-l', '元宇宙 次级商圈 地块 64㎡', '数字土地', 'blue', 96000, { desc: '投机属性强，价格与平台用户增长直接相关。' }],
  ['a-game-cart-collect', '传奇账号（全服前十）', '潮玩', 'blue', 66000, { desc: '版本更迭是最大风险，账号交易存在政策限制。' }],
  ['a-figure-studio', '雕塑工作室 原作', '手办', 'blue', 56000, { desc: '艺术属性带来溢价，鉴定与来源决定价格。' }],
  ['a-card-promo', '集换卡 赛事限定 promo', '卡牌', 'blue', 22000, { desc: '赛事限定发行量极小，需求集中在核心玩家。' }],
);

/* ------------------------------------------------------------------ 序列化 */
const j = (v) => JSON.stringify(v);
function line(row) {
  const [id, name, sub, rar, price, ex] = row;
  const extra = {};
  if (ex.float) extra.float = true;
  if (ex.st) extra.st = true;
  if (ex.pattern) extra.pattern = ex.pattern;
  if (ex.vol) extra.vol = ex.vol;
  if (ex.unit) extra.unit = ex.unit;
  extra.desc = ex.desc;
  return `  [${j(id)}, ${j(name)}, ${j(sub)}, ${j(rar)}, ${price}, ${j(extra)}],`;
}

function file(header, varName, rows) {
  const counts = rows.reduce((m, r) => ((m[r[3]] = (m[r[3]] || 0) + 1), m), {});
  const body =
    `/**\n * MONO — ${header}\n * 自动生成：node scripts/gen-catalog.mjs（请勿手改格式）\n` +
    ` * 字段: [id, name, subType, rarity, basePrice, extra]\n * 共 ${rows.length} 条 | ${JSON.stringify(counts)}\n */\n` +
    `export const ${varName} = [\n${rows.map(line).join('\n')}\n];\n`;
  return body;
}

/* ------------------------------------------------------------------ 校验 */
const problems = [];
const ids = new Set();
const names = new Set();
for (const [rows, label] of [
  [CS2, 'cs2'],
  [COMPUTE, 'compute'],
  [HARDWARE, 'hardware'],
  [ASSETS, 'assets'],
]) {
  for (const r of rows) {
    if (r.length !== 6) problems.push(`${label}: bad row length ${r[0]}`);
    if (ids.has(r[0])) problems.push(`${label}: duplicate id ${r[0]}`);
    ids.add(r[0]);
    if (names.has(r[1])) problems.push(`${label}: duplicate name ${r[1]}`);
    names.add(r[1]);
    if (!(r[4] > 0)) problems.push(`${label}: bad price ${r[0]}`);
    if (r[1].length > 40) problems.push(`${label}: long name ${r[1]}`);
    if (!r[5] || !r[5].desc) problems.push(`${label}: missing desc ${r[0]}`);
    if (/[\u{1F300}-\u{1FAFF}\u{2700}-\u{27BF}\u{2B00}-\u{2BFF}]/u.test(r[1] + r[5].desc)) problems.push(`${label}: emoji in ${r[0]}`);
  }
}
if (problems.length) {
  console.error('数据校验失败：\n' + problems.join('\n'));
  process.exit(1);
}

mkdirSync(OUT, { recursive: true });
writeFileSync(resolve(OUT, 'catalog-cs2.js'), file('CS2 枪械皮肤 / 饰品（真实市场锚价）', 'CS2', CS2));
writeFileSync(resolve(OUT, 'catalog-compute.js'), file('AI 算力资产', 'COMPUTE', COMPUTE));
writeFileSync(resolve(OUT, 'catalog-hardware.js'), file('电脑配件', 'HARDWARE', HARDWARE));
writeFileSync(resolve(OUT, 'catalog-assets.js'), file('虚拟股票 / 房产 / 收藏品', 'ASSETS', ASSETS));

const stat = (rows) =>
  rows.reduce((m, r) => ((m[r[3]] = (m[r[3]] || 0) + 1), m), {});
console.log('cs2     ', CS2.length, JSON.stringify(stat(CS2)));
console.log('compute ', COMPUTE.length, JSON.stringify(stat(COMPUTE)));
console.log('hardware', HARDWARE.length, JSON.stringify(stat(HARDWARE)));
console.log('assets  ', ASSETS.length, JSON.stringify(stat(ASSETS)));
console.log('total   ', CS2.length + COMPUTE.length + HARDWARE.length + ASSETS.length, '| unique ids', ids.size);
